package com.example.tnd.model
class DareData {
    val Compliments = listOf(
        "Compliment the person to your right.",
        "Say something nice to someone you don’t know well.",
        "Give a creative compliment about someone's outfit.",
        "Tell the person on your right the most charming thing about their personality.",
        "Compliment someone’s smile as if you’re writing a poem about it.",
        "Say three flattering things about the person sitting opposite you without repeating words.",
        "Give the player to your left the sweetest nickname you can think of.",
        "Tell someone at the table why they would make a great movie star.",
        "Give your most elegant compliment about someone’s outfit.",
        "Praise the person two seats away for something they probably don’t even notice about themselves.",
        "Invent a funny award for someone and tell them why they deserve it.",
        "Tell the group who here has the most contagious laugh and describe it in a flattering way.",
        "Say something nice about the hair of every person in the circle.",
        "Give someone a compliment about their sense of humor.",
        "Share why you think the person next to you would be an amazing friend for life.",
        "Tell someone why they’d win “Most Likely to Brighten a Room.”",
        "Compliment someone’s voice as if you’re an expert judge on a talent show.",
        "Say something heartwarming about another player’s kindness.",
        "Make up a glamorous title for someone and explain why they deserve it.",
        "Give someone an over-the-top compliment about their intelligence.",
        "Tell the group who you think has the best fashion sense here — and why.",
        "Say why you think the player across from you would make an amazing mentor.",
        "Flatter someone’s creativity in three unique ways.",
        "Tell someone what you admire about their confidence.",
        "Give the most playful compliment about someone’s dance skills.",
        "Share why you think someone here would make an awesome superhero.",
        "Tell the person beside you what makes them unforgettable.",
        "Compliment someone’s laugh as if it’s a rare melody.",
        "Say something lovely about someone’s eyes.",
        "Praise someone’s leadership qualities.",
        "Give a compliment about someone’s storytelling talent.",
        "Flatter someone about their ability to make others smile.",
        "Invent a slogan for how cool one of your friends is.",
        "Say why someone would totally ace a TV cooking show.",
        "Tell a player why they’d make the perfect motivational speaker.",
        "Compliment the neatest thing about someone’s handwriting (or texting style).",
        "Share a flattering comment about someone’s athletic skills.",
        "Compliment the person across from you on their taste in music.",
        "Say why you’d trust someone here with an important secret.",
        "Flatter someone’s sense of adventure.",
        "Compliment a player’s ability to make others feel welcome.",
        "Give a sweet comment about someone’s pet-friendly vibe (even if they don’t have one).",
        "Tell someone what makes them a great listener.",
        "Say which player would make the best movie hero and why.",
        "Compliment someone’s dedication to their hobbies.",
        "Flatter someone’s optimism.",
        "Praise a player’s style of speaking or storytelling.",
        "Give someone an imaginative compliment about their brainpower.",
        "Say something cute about someone’s facial expressions.",
        "Compliment the best thing about how someone walks or carries themselves.",
        "Give an elegant compliment about someone’s shoes or accessories.",
        "Tell someone they’d win an award for generosity — explain why.",
        "Compliment someone’s handwriting or drawing talent.",
        "Tell someone their kindness could light up a whole street.",
        "Flatter someone’s quick wit.",
        "Compliment the way someone stays calm under pressure.",
        "Tell someone what makes them a loyal friend.",
        "Say why a person here would make a great teacher.",
        "Compliment someone’s taste in movies or shows.",
        "Flatter someone’s ability to cheer people up.",
        "Give a sincere compliment about someone’s generosity.",
        "Say something sweet about someone’s determination.",
        "Praise a player’s sense of style using a fancy metaphor.",
        "Compliment someone’s talent for making people laugh.",
        "Say something adorable about someone’s dimples (if they have them).",
        "Give a sincere compliment to the person chosen by the group.",
        "Give a compliment to another player as decided by the group.",
        "Flirt with someone in the group in a funny way.",
        "Call a friend and tell them one thing you really admire about them.",
        "Tell someone why you think they’re amazing at something.",
        "Give a dramatic, over-the-top compliment to someone in the group.",
        "Compliment someone’s personality instead of appearance.",
        "Give a compliment to the person the group thinks gets the least compliments.",
        "Say something nice about someone in the room in a really silly voice.",
        "Write a short poem praising someone in the group.",
        "Compliment someone’s laugh in the funniest way possible.",
        "Give a compliment using only gestures (no words).",
        "Compliment someone’s style or outfit in a dramatic way.",
        "Make a toast to someone highlighting their best qualities.",
        "Compliment someone’s intelligence in a creative way.",
        "Give three genuine compliments to one person quickly.",
        "Sing a short song praising someone in the room.",
        "Say something flattering to someone you normally argue with.",
        "Compliment someone as if you’re a news reporter.",
        "Call someone outside the group and tell them a compliment sincerely.",
        "Pretend to be a celebrity while giving someone a compliment.",
        "Compliment someone in rhyme for extra flair.",
        "Give a compliment to someone using a movie quote.",
        "Make up a funny nickname for someone based on their best trait.",
        "Give a compliment in a whisper to someone so no one else hears it.",
        "Compliment someone as if you’re their personal hype person.",
        "Compliment someone while doing a silly dance.",
        "Tell a compliment to someone in slow motion like a dramatic movie scene.",
        "Compliment someone using a funny accent.",
        "Give a compliment to someone while pretending to be a robot.",
        "Compliment someone using only one word.",
        "Compliment someone’s social media profile in a funny way.",
        "Give a compliment while pretending you’re on a reality show.",
        "Compliment the most unexpected person in the room.",
        "Compliment someone as if you’re a poet from the 1800s.",
        "Say something nice about someone’s voice or tone.",
        "Compliment someone while making animal noises.",
        "Compliment someone’s favorite skill or hobby dramatically.",
        "Pretend you’re a motivational speaker and compliment someone.",
        "Compliment someone while acting like a game show host.",
        "Compliment someone in a foreign language (you can make it up if needed).",
        "Make up a fictional award and give it to someone in the group with a compliment.",
        "Give a genuine, specific compliment to every person in the room.",
        "Go around the circle and say one thing you like about each person's outfit right now.",
        "Send a voice message to a parent or family member telling them one thing you appreciate about them.",
        "Compliment a person chosen by the group in a Shakespearean-style monologue.",
        "Give a compliment without using the words 'nice,' 'good,' or 'pretty.'",
        "Post a story on social media praising the friend who has supported you the most. Tag them!",
        "Do an impression of someone chosen by the group, highlighting their best mannerism.",
        "Write a haiku complimenting the player who has lost the most rounds.",
        "Give a dramatic, over-the-top compliment to an inanimate object in the room.",
        "Text your best friend (who isn't here) and list three reasons why they're awesome.",
        "Let the group choose someone from your Instagram followers. DM them a sincere compliment.",
        "Give a compliment to a player chosen by the group using only a gesture or mime.",
        "Roast a player chosen by the group, then immediately reverse it into a heartfelt compliment.",
        "Serenade a player chosen by the group with two lines of a flattering love song.",
        "Draw a quick, flattering caricature of a player of your choice.",
        "Nominate someone for a 'Best Of' award and present it with a speech.",
        "For the next three rounds, begin every sentence you say with a compliment.",
        "Call a store/restaurant and compliment a (real or made-up) employee to their manager.",
        "Give a 30-second sales pitch 'selling' a player chosen by the group to the rest of the group.",
        "Compliment the host on their excellent taste in games, snacks, and friends. Be specific."

    )

    val Creative = listOf(
            "Draw a self-portrait with your eyes closed.",
            "Draw a funny picture of a person chosen by the group.",
            "Draw an imaginary animal and give it a name.",
            "Draw a famous celebrity in a silly way.",
            "Draw a picture using your non-dominant hand.",
            "Draw a scene from your favorite movie.",
            "Draw a picture of someone in the group without lifting your pen.",
            "Draw an object and let everyone guess what it is.",
            "Draw your favorite food in a funny way.",
            "Draw a superhero version of yourself.",
            "Dance without music for 1 minute.",
            "Dance like a robot for 1 minute.",
            "Dance like your favorite celebrity.",
            "Create a funny dance routine with someone else.",
            "Dance with your eyes closed for 30 seconds.",
            "Dance using only one hand and one foot.",
            "Sing your favorite song in a funny voice.",
            "Sing a nursery rhyme as dramatically as you can.",
            "Sing a song while making animal sounds.",
            "Sing a song in a different accent.",
            "Sing a song while dancing at the same time.",
            "Make up a song about someone in the group and perform it.",
            "Hum a song and let someone guess it.",
            "Pretend to be a famous singer while singing any song.",
            "Write and perform a 30-second rap about someone in the group.",
            "Draw a comic about a funny moment in the group.",
            "Draw your dream house.",
            "Draw a scene from your favorite cartoon.",
            "Draw a mix of two animals and show it to the group.",
            "Dance with a random object (like a bottle or book) in a funny way.",
            "Draw your dream vacation place.",
            "Draw a person chosen by the group as a superhero or villain.",
            "Sing a made-up song about a random object in the room.",
            "Draw your mood as a picture.",
            "Dance like you’re in a music video for 1 minute.",
            "Draw your favorite animal doing something funny.",
            "Draw a scene from a popular meme.",
            "Draw your favorite character in a funny situation.",
            "Dance to a random song picked by the group.",
            "Draw an abstract version of your favorite song.",
            "Act out a short play with dancing and singing for 1 minute.",
            "Draw a person chosen by the group using only your non-dominant hand.",
            "Sing the chorus of your favorite song like an opera singer.",
            "Dance in a way that shows your favorite snack.",
            "Draw a famous movie scene but replace the characters with potatoes.",
            "Sing the alphabet backwards in a dramatic way.",
            "Dance for 30 seconds using only your arms.",
            "Close your eyes and draw what you think an alien spaceship looks like.",
            "Lip-sync to a song chosen by the group with lots of emotion.",
            "Do the robot dance for 1 minute without stopping.",
            "Draw a person chosen by the group as a superhero and give them a name and power.",
            "Sing 'Happy Birthday' in the creepiest way you can.",
            "Make up a new dance move, name it, and show it to the group.",
            "Draw a comic showing how the game night is going.",
            "Sing the last text message you got like a nursery rhyme.",
            "Rap about the things on the table in front of you.",
            "Work with a person chosen by the group to draw a monster together without talking.",
            "Sing a popular song but replace all nouns with the word 'pickle'.",
            "Act out making a cup of coffee like a ballet dance.",
            "Draw a map of your favorite fictional world (like Hogwarts or Middle Earth).",
            "Do the Macarena at double speed.",
            "Sing a childhood commercial jingle with full energy.",
            "Draw the group's pet or imaginary spirit animal.",
            "Do a famous music video dance for 1 minute.",
            "Make up and sing a short jingle about the drink in your hand.",
            "Dance like you're waist-deep in jelly.",
            "Draw a perfect circle without looking at your paper.",
            "Sing a love song while making eye contact with someone.",
            "Do the worm or try your best.",
            "Draw what technology will look like in 50 years.",
            "Sing a song but hiccup after every 3 words.",
            "Do a dance from a different culture (do your best respectfully!).",
            "Draw a self-portrait without lifting your pen.",
            "Sing an emotional song and pretend to cry dramatically.",
            "Teach the group a simple line dance step.",
            "Draw a person chosen by the group as a vintage cartoon character.",
            "Sing a rock song like a tiny whispering mouse.",
            "Dance using only your head and shoulders.",
            "Create a quick mural on a large paper using 3 colors.",
            "Sing a duet with someone in the group for at least 30 seconds.",
            "Do a 'rain dance' to try to change the weather outside."

    )
    val Food = listOf(
        "Drink a 'mystery mix' of 3 ingredients chosen by the group.",
        "Eat a spoonful of a random condiment like ketchup, mustard, or mayo.",
        "Close your eyes and guess the food you taste.",
        "Mix two foods that don’t go together and eat it.",
        "Eat a fruit or vegetable without using your hands.",
        "Let someone feed you while you’re blindfolded.",
        "Take a shot of pickle juice or brine.",
        "Eat something sweet right after something sour.",
        "Lick a salty snack off someone’s arm.",
        "Eat a cracker or cookie and then try to whistle.",
        "Eat a food you normally dislike.",
        "Try a weird food combo picked by the group.",
        "Eat something with chopsticks if you’re not good at it.",
        "Take a big bite of a sandwich and say your full name.",
        "Eat whipped cream without licking your lips.",
        "Eat a snack with your hands behind your back.",
        "Let someone pour sauce on your hand and lick it off.",
        "Eat something very spicy and don’t react for 30 seconds.",
        "Guess a spice or herb by taste.",
        "Eat a food upside down.",
        "Eat using a funny or unusual utensil.",
        "Try a dipping sauce picked by the group.",
        "Eat something soft like pudding without a spoon.",
        "Eat something crunchy as loudly as possible.",
        "Eat a cold food then immediately eat a hot food.",
        "Eat while keeping eye contact with someone.",
        "Balance a small food on your nose and catch it in your mouth.",
        "Eat something and then try to blow a bubble with gum.",
        "Let the group decide the order you eat your foods.",
        "Eat something with extra seasoning.",
        "Drink a beverage from a bowl like a cat.",
        "Assemble and eat a taco or sandwich blindly.",
        "Take a bite and guess all the ingredients.",
        "Eat while singing a song.",
        "Try to eat a messy food neatly.",
        "Try a weird food combo like fries and ice cream.",
        "Eat a food you’ve never tried before.",
        "Eat a snack picked by someone else while blindfolded.",
        "Mix chocolate with something salty and eat it.",
        "Take a bite of raw onion or garlic.",
        "Try a very spicy chili.",
        "Drink a small random beverage (non-alcoholic).",
        "Eat a food with a strange texture like gelatin or pickles.",
        "Take a bite of ice cream with a spicy topping.",
        "Eat a vegetable you dislike.",
        "Try sweet and sour foods together.",
        "Eat a mystery food from a covered plate.",
        "Take a tiny spoon of hot sauce or chili paste.",
        "Eat a fruit in a funny way, like upside down.",
        "Make the weirdest face while eating.",
        "Eat food picked by the person across from you.",
        "Mix two drinks and drink it.",
        "Eat a candy with a strange texture.",
        "Try dessert and savory food together.",
        "Take a bite of very salty food.",
        "Eat a strange-flavored ice cream.",
        "Eat from someone else’s plate in the group.",
        "Mix something crunchy with something soft.",
        "Eat a bite without chewing first.",
        "Try a weird combo suggested by everyone.",
        "Eat something you normally wouldn’t touch.",
        "Eat a small bitter food.",
        "Eat a snack while holding your nose.",
        "Take a spoon of something sour like lime or tamarind.",
        "Try three very different foods together.",
        "Eat a weird candy without knowing the flavor.",
        "Eat something while being fed blindfolded.",
        "Taste a condiment straight from the bottle or packet."
    )

    val Group = listOf(
            "Do a funny walk across the room.",
            "Speak in a funny accent for 3 rounds.",
            "Dance with someone for 30 seconds.",
            "Act like an animal chosen by the group for 1 minute.",
            "Do a slow-motion walk.",
            "Imitate someone in the group until they guess.",
            "Form a human pyramid with 2 or more people.",
            "Do a group cheer for someone.",
            "Create a 30-second skit with 2 other players.",
            "Sing a song chorus together as a group.",
            "Make up a handshake with someone and show it.",
            "Do freeze dance where everyone stops when music stops.",
            "Act out a movie scene with the group.",
            "Form a conga line and walk around.",
            "Do a 1-minute group talent show act.",
            "Do group storytelling, each person adds a line.",
            "Make a funny commercial with 2 or 3 people.",
            "Have a mini dance battle with someone.",
            "Act like a job or profession and let the group guess.",
            "Play charades using only animal actions.",
            "Make a group pyramid pose and hold it.",
            "Create a 1-minute rap with 2 other people.",
            "Do a human knot and try to untangle.",
            "Act like zombies and walk around.",
            "Play musical chairs with the group.",
            "Do a synchronized dance move with 2 others.",
            "Invent a funny group handshake and show it.",
            "Have a group staring contest – last one blinking loses.",
            "Do a human statue pose based on a theme.",
            "Sing a song line by line with the group.",
            "Do a mini fashion show with funny poses.",
            "Perform a funny group skit.",
            "Form a human bridge or arch and let others pass under.",
            "Do a funny chant while hopping on one foot.",
            "Act out a cartoon scene as a group.",
            "Do a silent disco where everyone dances with headphones.",
            "Start a game of 'Never Have I Ever' with 5 questions.",
            "Be the hype person and cheer for everyone.",
            "Organize a 1-minute challenge using items in the room.",
            "Lead a conga line through 3 areas.",
            "Give everyone a funny nickname for 15 minutes.",
            "Start a slow clap that grows then stops.",
            "Narrate the next game like a sports announcer.",
            "Teach a handshake or secret hand gesture.",
            "Lead a silly warm-up routine.",
            "Start a word chain game with 10 words.",
            "Organize a staring contest and pick a winner.",
            "Count down 60 seconds dramatically for someone's turn.",
            "Start an improv scene with 3 random objects.",
            "Lead a silly group chant everyone performs.",
            "Start a round of 'Would You Rather' with 2 options.",
            "Lead a group sing-along of a popular chorus.",
            "Judge the next round and give funny feedback.",
            "Start a charades game with a prompt.",
            "Start a Mexican wave 3 times around the group.",
            "Lead a 'show and tell' with items from pockets.",
            "Lead a group dance-off starting with a 15-second move.",
            "Make a limerick about the host and recite it.",
            "Start 'Two Truths and a Lie' with yourself first.",
            "Introduce players with funny names like a game show host.",
            "Lead a breathing exercise with funny sounds.",
            "Start a thumb war tournament and crown a winner.",
            "Start a compliment chain around the circle.",
            "Lead a 'Rock, Paper, Scissors' tournament.",
            "Take a group selfie with a funny theme.",
            "Start applause for a random object.",
            "Translate what someone says into gibberish.",
            "Start 'Categories' game naming items from a category.",
            "Lead balancing an object on your head for 30 seconds.",
            "Start a 'story chain' with each person adding a sentence.",
            "Vote for best-dressed and give a small award."

    )

    val Mystery = listOf(
        "Spin around 10 times and try to walk straight.",
        "Wear a funny hat or item for 3 turns.",
        "Speak in rhymes until your next turn.",
        "Swap an item of clothing with someone for 1 turn.",
        "Act like a celebrity chosen by the group for 1 minute.",
        "Do 10 jumping jacks while singing a song.",
        "Talk in a baby voice until your next turn.",
        "Balance a book on your head for 1 minute.",
        "Say a tongue twister 3 times fast.",
        "Walk backward across the room.",
        "Let someone write a funny word on your forehead.",
        "Hold a funny pose until your next turn.",
        "Make a silly face for 30 seconds.",
        "Talk only in questions until your next turn.",
        "Pretend to be a waiter and serve imaginary food.",
        "Act like a chicken and make noises for 30 seconds.",
        "Do your best cartoon character impression.",
        "Try to lick your elbow for 30 seconds.",
        "Wear socks on your hands for the next turn.",
        "Hop on one foot across the room.",
        "Pretend you are invisible for 1 minute.",
        "Make a secret handshake with someone.",
        "Act like a statue for 1 minute.",
        "Do a funny penguin walk across the room.",
        "Speak like a pirate until your next turn.",
        "Pretend you are an elevator operator for 1 minute.",
        "Move in slow motion for 30 seconds.",
        "Pretend to faint dramatically onto a chair.",
        "Try to touch your nose with your tongue.",
        "Sing the alphabet backwards as fast as you can.",
        "Pretend you are underwater for 30 seconds.",
        "Mimic the person on your left for 1 minute.",
        "Make a short commercial for an imaginary product.",
        "Try to juggle 3 objects from the room.",
        "Pretend to be a robot and dance.",
        "Do a funny runway walk across the room.",
        "Pretend to be a cat and meow for 30 seconds.",
        "Speak only in movie quotes until your next turn.",
        "Do 5 push-ups while making a silly face.",
        "Pretend to be a superhero and pose for 30 seconds.",
        "Make a short chant and have everyone repeat it.",
        "Open a random Wikipedia article and act out the title.",
        "Combine 2 random objects and make a short commercial.",
        "Spin a bottle and do the dare the bottle points to.",
        "Pick a number 1-20 and do that many push-ups or squats.",
        "Go to a window and wave at the first person or car you see.",
        "Blindfolded, taste a mystery food chosen by the group.",
        "Text a random word to a contact chosen by the group.",
        "Draw a random word from a hat and sing about it for 30 seconds.",
        "Act out a random emoji chosen by the group.",
        "Call a friend and say the first random sentence the group tells you.",
        "Do an interpretive dance of a random movie title chosen by the group.",
        "Dance to a random song picked by the group for 1 minute.",
        "Go outside and take a photo of something interesting in 60 seconds.",
        "Switch two items in the room and see how long it takes for someone to notice.",
        "Speak in a random accent chosen by the group for 3 turns.",
        "Pick a random page from a book and read the first sentence dramatically.",
        "Do a magic trick with a random object or pretend convincingly.",
        "Take a selfie with a random filter chosen by the group.",
        "High-five 5 objects in the room and explain why each deserves it.",
        "Imitate a random celebrity drawn from a hat.",
        "Blindfolded, guess which 3 items were moved on the table.",
        "Give a random compliment to a stranger or friend.",
        "Make a story using 3 random words from the group.",
        "Do a handstand against the wall or try your best.",
        "Act out an event from a random year chosen by the group.",
        "Move to a new spot in the room randomly after your turn.",
        "Send a voice message saying 'banana' for the number of seconds chosen by the group.",
        "Draw a random shape with your eyes closed and finish it based on the group's idea.",
        "Change your phone language setting randomly for 1 hour.",
        "Tell a story about a random item from your bag or pocket.",
        "Do a task using only your non-dominant hand.",
        "Use a silly word in conversation naturally for 1 minute.",
        "Act out a random superpower given by the group for 30 seconds.",
        "Pick a random country and speak in its accent for 2 turns.",
        "Assign everyone a role in a movie and explain the plot.",
        "Find 3 objects of a random color chosen by the group in 30 seconds.",
        "Imitate a random animal until someone guesses it.",
        "Swap a clothing item with the person to your left for 1 round.",
        "Act out a random profession for 1 minute.",
        "Close your eyes, spin 5 times, and walk to a target chosen by the group."
    )


    val Pranks = listOf(
        "Call a friend and give them a funny award.",
        "Text someone a silly or confusing message without explaining it.",
        "Send a dramatic voice note about a silly situation.",
        "Post a funny social media status tagging a friend.",
        "Call a friend and sing a random song.",
        "Send a random GIF and see their reaction.",
        "Pretend to be someone else in a text for 1 minute.",
        "Send a mystery emoji sequence and see if they guess it.",
        "Call a friend pretending you lost something absurd.",
        "Text a random compliment to someone.",
        "Pretend to be an automated service in a call.",
        "Send a voice note of your best animal impression.",
        "Text a fake but harmless rumor about yourself.",
        "Call a friend and ask a silly riddle.",
        "Send a picture of a random object and act like it’s important.",
        "Pretend to be a fortune teller and send a prediction.",
        "Send a voice note making random sound effects.",
        "Text a challenge for your friend to complete in 1 minute.",
        "Call pretending to announce silly breaking news.",
        "Send a picture of your shoes and ask them to guess your socks' color.",
        "Pretend to be lost and ask silly directions.",
        "Send a funny song lyric as a secret code.",
        "Call and act like they won an imaginary prize.",
        "Text a random absurd question like 'Do cats fly?'",
        "Send a silly filter selfie and claim it’s important ID.",
        "Pretend to be a movie character in a text conversation.",
        "Call and whisper dramatically for 30 seconds.",
        "Send a picture of a random household item and ask for advice.",
        "Text a fake countdown to a made-up event.",
        "Call pretending to speak a foreign language.",
        "Send a voice note pretending to be in a silly dangerous situation.",
        "Text pretending you are a famous celebrity needing help.",
        "Send a random sound clip and ask them to guess it.",
        "Call and ask advice about something ridiculous.",
        "Text a funny joke but act serious.",
        "Send a photo of your messy room and call it a museum exhibit.",
        "Call and narrate their life story.",
        "Text pretending you are writing a secret mission report.",
        "Pretend to report a 'mystery event' in your house.",
        "Text a riddle and act intense about the answer.",
        "Call and speak only in rhymes for 1 minute.",
        "Send a voice note with dramatic sound effects and say it’s urgent.",
        "Call a pizza place and ask if they can deliver one slice (don’t actually order).",
        "Text your friend a confusing message about seeing them outside.",
        "Sign them up for a weird but harmless email newsletter.",
        "Call a store and ask about a 'lost item' like a pet rock.",
        "Text a photo of an empty chair saying: 'Why did you leave?'",
        "Pretend to be a wrong number and ask confusing questions about 'the package.'",
        "Call pretending to survey them about alien abductions.",
        "Text: 'Your doorbell is ringing nonstop. Are you expecting 20 packages?'",
        "Change their Netflix profile name to something funny (if you can).",
        "Send a whispery voice note: 'I can see you.'",
        "Text a mysterious clue like: 'It’s under the third rose bush.'",
        "Call pretending to be 'Captain Sparklebeard' from the Intergalactic Postal Service.",
        "Sign them up for a silly text alert, like daily llama facts.",
        "Send a photo of a random object and say: 'It’s done. They’ll never suspect.'",
        "Ask if their fridge is running and say you’ll come help.",
        "Send a message: 'The squirrels are watching.'",
        "Text a fake parking ticket photo: 'Move your car ASAP.'",
        "Call in a fake accent claiming to be a long-lost relative.",
        "Text: 'I buried the thing behind the old oak tree.'",
        "Send: 'The council of owls approved your application. Expect a hoot at midnight.'",
        "Call pretending to be a time traveler warning of minor problems.",
        "Text a nervous-looking GIF with: 'They know. Act normal.'",
        "Send a voice message with sirens saying: 'It’s happening. Meet at the spot.'",
        "Text: 'I hid the treasure. Start where we first met.'",
        "Call: 'This is Gary from Gary’s Pillow Fluffing Service. Your pillows need fluffing.'"

    )

    val Silly = listOf(
        "Make the silliest face you can and hold it for 30 seconds.",
        "Talk in a funny voice until your next turn.",
        "Walk across the room like a crab.",
        "Pretend to be a chicken and flap your wings for 30 seconds.",
        "Do your best impression of a cartoon character.",
        "Sing a song using only gibberish.",
        "Act like a superhero with an imaginary power for 1 minute.",
        "Wear a funny hat or item of clothing for the next 3 rounds.",
        "Dance like no one is watching for 1 minute.",
        "Pretend to be a robot and move mechanically for 30 seconds.",
        "Make up a silly handshake with someone in the group.",
        "Talk only in rhymes for the next 2 rounds.",
        "Do 5 silly poses in a row like a runway model.",
        "Pretend to be a mime trapped in an invisible box.",
        "Walk backwards while balancing an object on your head.",
        "Pretend to be underwater and swim around the room.",
        "Do a dramatic slow-motion action scene of your choice.",
        "Pretend to be an alien trying to communicate with humans.",
        "Speak in a funny accent until your next turn.",
        "Imitate someone else in the group until they guess who it is.",
        "Do your best impression of a baby for 1 minute.",
        "Sing the alphabet backwards in a funny voice.",
        "Pretend to trip and fall dramatically (safely).",
        "Make animal noises for 30 seconds.",
        "Pretend to be a statue and freeze until someone touches you.",
        "Do a silly dance with exaggerated moves for 1 minute.",
        "Pretend to be a famous celebrity giving an interview.",
        "Talk like a pirate for the next 3 rounds.",
        "Make up a short, goofy story and act it out.",
        "Pretend to be a fashion model and walk across the room.",
        "Do your best impression of a clumsy person for 1 minute.",
        "Make a silly face and hold it while someone takes a photo.",
        "Pretend to be a talking animal and interact with the group.",
        "Speak in gibberish and see who can guess what you mean.",
        "Pretend to be extremely scared of an invisible object.",
        "Act like you’re in a soap opera and overreact to everything.",
        "Make a funny commercial for a random object in the room.",
        "Do a funny dance battle with someone else in the group.",
        "Pretend to be a superhero and strike dramatic poses.",
        "Talk like a robot for 1 minute and respond mechanically.",
        "Imitate a celebrity’s laugh as exaggerated as possible.",
        "Pretend to be a character from a movie and act it out.",
        "Put socks on your hands and give a dramatic speech.",
        "Wear a colander or strainer as a hat for 10 minutes.",
        "Have a 1-minute conversation saying only 'banana' with different expressions.",
        "Do a silly walk every time you enter or leave the room.",
        "Try to lick your elbow (even if you can’t).",
        "Sing the national anthem like a crying baby.",
        "Balance a spoon on your nose for 30 seconds.",
        "Do an interpretive dance of a washing machine.",
        "Try to blow a bubble with gum and let it pop on your face.",
        "Let the group style your hair using anything they can find.",
        "Have a staring contest with a wall and lose dramatically.",
        "Try to tie your shoes with eyes closed while narrating like a sports commentator.",
        "Make up a theme song for yourself and perform it.",
        "Do 10 jumping jacks while singing 'Twinkle, Twinkle, Little Star'.",
        "Wear all your clothes backwards for 20 minutes.",
        "Do your best impression of a dramatic soap opera actor.",
        "Pretend you are a secret agent from Mars.",
        "Speak in third person for 15 minutes.",
        "Do the Macarena backwards.",
        "Attempt to juggle three soft objects.",
        "Make a secret handshake with the person to your right.",
        "Pretend you’re a celebrity and give autographs to everyone.",
        "Try to draw a picture with the pencil in your teeth.",
        "Do a fashion show with the silliest outfit you can make.",
        "Attempt a 30-second breakdance.",
        "Create a sculpture using only snacks and present it as art.",
        "Do a dramatic movie trailer impression for your life.",
        "Attempt to do the worm across the floor.",
        "Sing everything you say for 5 minutes.",
        "Pretend you are a mirror and copy someone for 2 minutes.",
        "Try to convince everyone you can talk to furniture.",
        "Do a dramatic reading of a takeout menu.",
        "Attempt to make a bird sound with your hands.",
        "Walk like a penguin every time you get up for an hour.",
        "Create a new dance move and teach it to everyone."
    )

    val SocialMedia = listOf(
        "Post a funny selfie with a silly caption.",
        "Post a throwback picture and tag a friend with a funny comment.",
        "Record a 15-second lip-sync video to a random song.",
        "Post a funny TikTok dance and tag a friend.",
        "Share a random, goofy fact about yourself.",
        "Post a photo of your messy room proudly.",
        "Take a funny Boomerang video and share it.",
        "Post a story with a silly filter and be dramatic.",
        "Upload a picture pretending to be a celebrity.",
        "Post a story imitating a famous meme.",
        "Post a video of yourself doing a weird dance in public.",
        "Upload a story pretending to be someone else for 1 hour.",
        "Post a funny face selfie without explanation.",
        "Share a random household item and act like it’s luxury.",
        "Post a story asking followers a silly question.",
        "Record a short, funny tutorial and post it.",
        "Post a story pretending to be a motivational speaker.",
        "Take a selfie with a goofy expression and dramatic caption.",
        "Post a funny animal video with a ridiculous commentary.",
        "Upload a photo pretending to be in an exotic location.",
        "Record a silly TikTok acting out a random scenario.",
        "Post a video attempting a trending challenge.",
        "Upload a story acting like a dramatic soap opera star.",
        "Post a photo of a random object and ask followers to guess it.",
        "Record yourself singing a song in a silly voice and post it.",
        "Post a story imitating a famous movie scene.",
        "Upload a funny reaction video to something random.",
        "Record a short prank video and share it.",
        "Post a story with a filter and tell a dramatic story.",
        "Upload a funny meme you made and tag friends.",
        "Post a video pretending to be your pet.",
        "Record a fake product review video and share it.",
        "Post a story doing a dramatic slow-motion action.",
        "Upload a funny photo with a random object on your head.",
        "Post a story pretending to be a chef giving silly tips.",
        "Record a ridiculous dance challenge video and post it.",
        "Post a story pretending to be a superhero saving the day.",
        "Upload a funny impression of someone famous.",
        "Post a photo making the silliest expression possible.",
        "Record a 15-second story using only gestures.",
        "Post a story reacting dramatically to an ordinary event.",
        "Post a story with a poll asking something silly and tag the group.",
        "Upload a photo of your foot with a cryptic caption.",
        "Change your profile picture to a meme the group chooses for 1 hour.",
        "Post a video attempting a viral dance trend.",
        "Share an embarrassing childhood photo with a funny caption.",
        "Go live for 60 seconds and silently smile at the camera.",
        "Post a picture of the sky with a funny or confusing quote.",
        "Create a poll asking followers to choose your next silly hairstyle.",
        "Share a screenshot of your most-played song with a funny caption.",
        "Post a quiz result and act like it’s incredibly accurate.",
        "Upload a video giving a fake tutorial about something.",
        "Change your bio to something the group writes for 24 hours.",
        "Post a picture of your food with an overly dramatic review.",
        "Share a selfie with a weird filter and pretend it’s your new look.",
        "Create a story asking for advice on a made-up problem.",
        "Post a video lip-syncing to a famous movie monologue.",
        "Share a photo of a random object and ask followers to guess it.",
        "Go live and answer group questions for 3 minutes.",
        "Post a 'get ready with me' story for brushing your teeth.",
        "Share a motivational quote over a photo of your pet or plant.",
        "Upload a video trying to speak a language you don’t know.",
        "Post a cryptic message and leave it unexplained.",
        "Share a picture of your screen showing this game and tag friends.",
        "Create a poll asking if you should start a silly business.",
        "Post a story asking 'What should I do tonight?' and do the top suggestion.",
        "Share a video attempting a viral fitness challenge.",
        "Upload a photo from a weird angle with a funny caption.",
        "Post a screenshot of your battery at 1% with a dramatic caption.",
        "Share a makeup tutorial using wrong products for fun.",
        "Go live and read a cereal box dramatically.",
        "Post a picture of your messy room with a funny caption.",
        "Share a video trying to explain something you know nothing about.",
        "Upload a story with a countdown timer and no explanation.",
        "Post a selfie with someone else's pet pretending it's yours.",
        "Share a 'day in the life' story that’s completely fictional."

    )

    val Tech = listOf(
        "Change your phone wallpaper to a funny meme.",
        "Send the last photo in your camera roll to a random friend.",
        "Call a friend and speak only in emojis for one minute.",
        "Text the last person you messaged a joke.",
        "Post a selfie making your silliest face.",
        "Record a 10-second video singing a random song.",
        "Change your ringtone to a funny sound for the next hour.",
        "Send a voice note saying a tongue twister as fast as you can.",
        "Change your phone wallpaper to a group-chosen photo for one hour.",
        "Send a meme to a friend without explanation.",
        "Post a photo of an object in the room in a funny way.",
        "Call a friend and talk in a cartoon character voice for one minute.",
        "Send a random GIF to someone in your contacts.",
        "Change your keyboard theme to something silly for the next hour.",
        "Record a video saying your favorite quote dramatically.",
        "Text the last person you messaged a compliment using only emojis.",
        "Post a selfie wearing something silly on your head.",
        "Send a voice note pretending to narrate your breakfast.",
        "Change your contact photo for a friend to something funny.",
        "Take a photo of your shoes and post it with a creative caption.",
        "Text a friend the name of your favorite snack.",
        "Post a short video dancing to a random song on your phone.",
        "Record a video counting to ten in a funny voice.",
        "Send a GIF reacting to the last thing someone sent you.",
        "Change your app icons to funny images temporarily.",
        "Text a random friend a positive message.",
        "Record a 15-second video singing the alphabet backwards.",
        "Post a photo holding an unusual object from your room.",
        "Call a friend and whisper everything you say for 30 seconds.",
        "Send a voice note telling a short joke.",
        "Take a selfie with a household object in your hand.",
        "Post a photo of your hand in a silly pose.",
        "Text the last person you messaged with a riddle.",
        "Record a video counting your fingers and toes simultaneously.",
        "Send a funny sticker to a friend.",
        "Change your wallpaper to a celebrity photo for one hour.",
        "Take a photo of your ceiling and post it creatively.",
        "Text someone your favorite emoji sequence.",
        "Record a 10-second video clapping in a funny rhythm.",
        "Post a photo of your phone with an unusual angle.",
        "Call a friend and tell a 15-second funny story.",
        "Send a screenshot of your home screen with a creative caption.",
        "Change your alarm sound to something silly for tomorrow morning.",
        "Record a video spelling your name backwards.",
        "Post a selfie with a peace sign in a funny location.",
        "Text a friend a made-up word and its definition.",
        "Send a voice note pretending to be a sports commentator.",
        "Take a photo of an everyday object and caption it dramatically.",
        "Post a short video saying your favorite word five times.",
        "Call a friend and tell them three random facts about your day.",
        "Send a GIF that matches your current mood.",
        "Change your lock screen to a group-chosen photo for one hour.",
        "Record a video clapping your hands to a rhythm you make up.",
        "Text the last person you messaged a funny question.",
        "Post a selfie with an exaggerated smile.",
        "Send a meme from your gallery to a friend.",
        "Record a 15-second video counting numbers in a silly voice.",
        "Change your phone wallpaper to a cartoon for one hour.",
        "Send a voice note saying your favorite joke.",
        "Post a photo holding a random household object.",
        "Text a friend the name of a song you like.",
        "Record a video pretending to recite a dramatic poem.",
        "Change your ringtone to a song chorus for one hour.",
        "Send a sticker to a group chat with a funny caption.",
        "Take a selfie making a surprised face.",
        "Post a photo of your feet in a silly pose.",
        "Text someone your favorite random fact.",
        "Record a video naming your top three favorite snacks.",
        "Send a GIF to a friend reacting to nothing in particular.",
        "Change your keyboard color to the brightest option for an hour.",
        "Post a short video saying a tongue twister correctly.",
        "Take a photo of your desk from a funny angle.",
        "Text a friend a compliment using only emojis.",
        "Record a video of yourself spinning in your chair.",
        "Send a voice note saying a random word repeatedly.",
        "Change your wallpaper to a group-selected silly image.",
        "Post a selfie with an exaggerated pout.",
        "Text the last person you messaged a random joke.",
        "Record a 10-second video saying 'hello' in as many accents as possible.",
        "Send a sticker to a friend without context.",
        "Take a photo of your reflection making a funny face.",
        "Post a photo of something you normally ignore creatively.",
        "Text a friend to ask the weirdest question you can think of.",
        "Record a video counting backwards from 20.",
        "Send a voice note singing one line of a random song.",
        "Change your lock screen image to a funny GIF for one hour.",
        "Post a selfie while winking with both eyes.",
        "Text someone a made-up emoji story.",
        "Record a video pretending to be a news reporter for one minute.",
        "Send a random meme to a friend with a silly caption.",
        "Take a photo of a common item and give it a dramatic title.",
        "Post a short video clapping and stomping to make a rhythm.",
        "Text a friend your favorite joke in under 10 words.",
        "Record a video of yourself hopping in place for 10 seconds.",
        "Send a voice note describing your last meal dramatically.",
        "Change your wallpaper to a funny pet photo for an hour.",
        "Post a selfie sticking your tongue out.",
        "Text a friend asking a random question about the future.",
        "Record a 15-second video acting like a famous celebrity.",
        "Send a sticker to the last group chat you messaged.",
        "Take a photo of your hand holding a random object.",
        "Post a short video counting your steps in a funny voice.",
        "Text someone a made-up nickname for themselves.",
        "Record a video naming five random objects in your room.",
        "Send a GIF to a friend that represents your mood today.",
        "Change your alarm tone to a short clip of a funny sound.",
        "Post a photo of a food item with a silly caption.",
        "Text a friend a random compliment.",
        "Record a video pretending your phone is an award for best performance.",
        "Send a voice note pretending to give a weather forecast."

    )

    val TimeGames = listOf(
        "Complete a challenge in 30 seconds.",
        "Try to balance on one foot for 1 minute.",
        "Count to 50 as fast as possible without mistakes.",
        "Stack 10 coins on top of each other in 30 seconds.",
        "Balance a book on your head for 1 minute.",
        "Tap a pen on the table 50 times in 20 seconds.",
        "Draw a simple house in 60 seconds.",
        "Clap your hands 30 times in 15 seconds.",
        "Do 10 jumping jacks in 15 seconds.",
        "Write your name with your non-dominant hand in 30 seconds.",
        "Try to keep a balloon in the air for 1 minute without it touching the ground.",
        "Touch your toes 20 times in 30 seconds.",
        "Count to 50 out loud as fast as possible in 30 seconds.",
        "Stack 5 coins using only one hand in 20 seconds.",
        "Balance a spoon on your nose for 30 seconds.",
        "Do 5 push-ups in 20 seconds.",
        "Say the alphabet backwards in 30 seconds.",
        "Draw a stick figure as fast as possible in 20 seconds.",
        "Hop on one foot for 30 seconds.",
        "Spin around 10 times in 15 seconds.",
        "Build a card tower in 1 minute.",
        "Do 10 squats in 20 seconds.",
        "Write a funny word as many times as possible in 30 seconds.",
        "Pass a pen from your chin to your nose in 30 seconds.",
        "Blow up a balloon and keep it in the air for 30 seconds.",
        "Stack 3 cups in a pyramid in 20 seconds.",
        "Draw a simple animal in 30 seconds.",
        "Balance a coin on your elbow for 20 seconds.",
        "Touch your knees and then the ceiling 10 times in 30 seconds.",
        "Say a tongue twister 5 times fast in 20 seconds.",
        "Do as many sit-ups as possible in 30 seconds.",
        "Spin a pen on the table for 30 seconds.",
        "Stack 4 small objects in a line in 20 seconds.",
        "Keep your feet off the floor while sitting in a chair for 30 seconds.",
        "Draw a smiley face with your eyes closed in 20 seconds.",
        "Clap your hands and stomp your feet 20 times in 30 seconds.",
        "Balance a straw on your finger for 20 seconds.",
        "Write your favorite word as many times as possible in 30 seconds.",
        "Hop from one spot to another 10 times in 30 seconds.",
        "Do 10 mountain climbers in 20 seconds.",
        "Spin in a circle 5 times and then walk straight in 20 seconds.",
        "Stack 3 pencils in a line in 20 seconds.",
        "Touch your ears, shoulders, knees, and toes in 20 seconds.",
        "Draw a simple heart in 15 seconds.",
        "Do 5 push-ups and clap in between in 30 seconds.",
        "Balance a coin on its edge for 20 seconds.",
        "Say the months of the year backwards in 30 seconds.",
        "Do 15 jumping jacks in 30 seconds.",
        "Write your initials in a funny way in 20 seconds.",
        "Keep a ball in the air by hitting it with your hand for 30 seconds.",
        "Draw a simple tree in 30 seconds.",
        "Stack 5 small objects on top of each other in 30 seconds.",
        "Touch your toes 5 times without bending your knees in 20 seconds.",
        "Hop on one foot and spin 3 times in 30 seconds.",
        "Write a short funny sentence in 30 seconds.",
        "Do 10 squats as fast as possible in 20 seconds.",
        "Balance a spoon on your hand for 30 seconds.",
        "Draw a simple car in 30 seconds.",
        "Count to 100 by 2’s in 30 seconds.",
        "Stack 4 coins on top of each other in 30 seconds.",
        "Do 10 lunges in 30 seconds.",
        "Say your favorite color 10 times fast in 20 seconds.",
        "Touch the floor and then the ceiling 5 times in 20 seconds.",
        "Spin around while clapping your hands 10 times in 30 seconds.",
        "Build a small tower with 5 objects in 20 seconds.",
        "Write the word 'fun' as many times as possible in 20 seconds.",
        "Do 5 sit-ups while raising your arms in 20 seconds.",
        "Balance a pen on your finger for 20 seconds.",
        "Draw a funny face on a piece of paper in 20 seconds.",
        "Hop from one foot to the other 15 times in 30 seconds.",
        "Stack 3 pencils vertically in 20 seconds.",
        "Say a tongue twister as many times as possible in 30 seconds.",
        "Do 10 jumping jacks while making a silly noise in 20 seconds.",
        "Write the alphabet backwards in 30 seconds.",
        "Balance a coin on your finger for 30 seconds.",
        "Touch your knees and then the ceiling 10 times in 30 seconds.",
        "Spin around 7 times and then walk straight in 30 seconds.",
        "Draw a star in 20 seconds.",
        "Stack 5 cups in a pyramid in 30 seconds.",
        "Do 5 push-ups while making a funny face in 30 seconds.",
        "Clap your hands 40 times in 30 seconds.",
        "Write a short rhyme in 30 seconds.",
        "Balance a small object on your head for 30 seconds.",
        "Hop from one foot to another 20 times in 30 seconds.",
        "Do 15 mountain climbers in 30 seconds.",
        "Draw a simple house in 20 seconds.",
        "Stack 3 coins in a line in 20 seconds.",
        "Touch your toes and then jump 5 times in 30 seconds.",
        "Say a funny word as many times as possible in 20 seconds.",
        "Spin in a circle and stop perfectly straight in 20 seconds.",
        "Write your favorite number 10 times in 15 seconds.",
        "Do 10 squats while counting out loud in 20 seconds.",
        "Balance a pen between your fingers for 20 seconds.",
        "Draw a smiley face while blindfolded in 30 seconds.",
        "Clap and stomp 15 times in 20 seconds.",
        "Stack 4 small objects in 30 seconds.",
        "Touch your ears, shoulders, knees, and toes in 30 seconds.",
        "Do 5 push-ups while spinning 1 time in 30 seconds.",
        "Write a funny word backwards in 20 seconds.",
        "Balance a coin on the back of your hand for 20 seconds.",
        "Draw a simple car or bike in 30 seconds.",
        "Hop on one foot and count to 20.",
        "Stack 5 coins as high as possible in 30 seconds.",
        "Touch your toes 10 times in 20 seconds.",
        "Say a tongue twister 3 times fast in 15 seconds.",
        "Spin a pen or pencil on a table for 30 seconds.",
        "Draw a simple tree in 20 seconds.",
        "Do 10 lunges while counting loudly in 20 seconds.",
        "Balance a small object on your finger while standing for 20 seconds.",
        "Write a silly sentence in 30 seconds.",
        "Stack 3 pencils vertically in 30 seconds.",
        "Hop from side to side 15 times in 30 seconds."

    )

    val Acting = listOf(
        "Pretend you are a famous celebrity giving an interview.",
        "Act like a superhero saving someone in the room.",
        "Pretend to be a villain plotting something dramatic.",
        "Mimic a character from your favorite TV show or movie.",
        "Act like a news reporter telling a funny story.",
        "Pretend you are a chef giving a cooking show.",
        "Roleplay as a teacher giving a lecture on a silly topic.",
        "Pretend to be a model walking on a fashion runway.",
        "Act like a famous singer performing on stage.",
        "Roleplay as a detective solving a funny mystery.",
        "Pretend to be a coach motivating a team dramatically.",
        "Act like a zombie walking around the room.",
        "Roleplay as a pirate searching for hidden treasure.",
        "Pretend to be an animal and interact with the group.",
        "Act like a dramatic soap opera character.",
        "Roleplay as a fortune teller predicting someone's future.",
        "Pretend you are a robot and only respond mechanically.",
        "Act like a character in a horror movie for 1 minute.",
        "Pretend to be a teacher giving a lesson on an imaginary subject.",
        "Roleplay as a superhero in a dramatic fight scene.",
        "Act like a famous comedian telling jokes.",
        "Pretend you are a talk show host interviewing someone.",
        "Roleplay as a character from a fairy tale.",
        "Pretend to be a ghost and gently scare someone.",
        "Act like a news anchor reporting ridiculous events.",
        "Pretend to be a motivational speaker giving advice.",
        "Roleplay as an alien learning about humans.",
        "Act like a dancer performing a dramatic routine.",
        "Pretend to be a sports commentator narrating a silly game.",
        "Roleplay as a shopkeeper selling imaginary products.",
        "Act like a character in a musical.",
        "Pretend to be a famous influencer promoting a ridiculous product.",
        "Roleplay as a superhero sidekick giving advice.",
        "Act like a magician performing a magic trick.",
        "Pretend to be a famous historical figure giving a speech.",
        "Roleplay as a pirate giving commands to the crew.",
        "Act like a cat or dog and interact with the group.",
        "Pretend to be a travel guide showing the room as a destination.",
        "Roleplay as a character from a horror story.",
        "Act like a teacher giving a funny quiz.",
        "Pretend to be a famous actor and reenact a dramatic scene.",
        "Roleplay as a knight on a mission to save the day.",
        "Act out a dramatic scene where you're a villain revealing your evil plan.",
        "Pretend you're a weather reporter giving a forecast for a zombie apocalypse.",
        "Do an impression of a famous movie character until someone guesses it.",
        "Act out a scene selling a ridiculous product (like a spoon that tells lies).",
        "Perform a dramatic monologue as a Shakespearean actor discovering Wi-Fi.",
        "Roleplay as a detective interrogating someone about a stolen cookie.",
        "Act out a scene as a superhero with a useless power (like turning left super fast).",
        "Do an impression of the person to your right ordering at a fancy restaurant.",
        "Perform a scene as a game show host hosting a boring task.",
        "Act out a silent movie scene escaping from invisible butterflies.",
        "Roleplay as a chef giving a cooking tutorial for a dish that doesn't exist.",
        "Do an impression of a reality TV star having a dramatic breakdown.",
        "Act out a scene as a tour guide giving a tour to aliens.",
        "Perform a dramatic reading of a fast food menu like ancient poetry.",
        "Roleplay as a therapist giving advice to a talking chair.",
        "Do an impression of a sports commentator narrating someone brushing teeth.",
        "Act out a scene as a spy who's bad at being sneaky.",
        "Perform a dramatic scene saying goodbye to your favorite sock.",
        "Roleplay as a news anchor reporting breaking news in the room.",
        "Do an impression of a dramatic actor forgetting lines in the middle of a performance.",
        "Act out a scene as a wizard trying to use modern technology.",
        "Perform a job interview for a professional napper.",
        "Roleplay as a romantic lead trying to seduce a piece of furniture.",
        "Do an impression of a nature documentary narrator describing someone searching for snacks.",
        "Act out a scene as a time traveler confused by everyday objects.",
        "Perform a dramatic death scene because you ran out of your favorite snack.",
        "Roleplay as a judge in a court case about the last slice of pizza.",
        "Do an impression of a celebrity giving a masterclass in something ridiculous.",
        "Act out a scene as an explorer discovering the lost remote control.",
        "Perform a dramatic reading of the ingredients list from a snack package.",
        "Roleplay as a motivational speaker giving a pep talk to a potted plant.",
        "Do an impression of a movie trailer voiceover for The Story of This Game Night.",
        "Act out a scene as a cowboy trying to herd cats.",
        "Perform a dramatic interpretation of a printer error message.",
        "Roleplay as a royal monarch giving commands to your subjects.",
        "Do an impression of a sports coach giving a halftime speech about a board game.",
        "Act out a scene as a scientist presenting the discovery of a new color.",
        "Perform a dramatic scene breaking up with your phone.",
        "Roleplay as a magical genie who mishears wishes.",
        "Do an impression of a historical figure reacting to modern technology."

    )


    val Confessions = listOf(
        "Confess a secret crush on a fictional character.",
        "Confess the silliest lie you’ve ever told.",
        "Say the weirdest thing you’ve ever Googled.",
        "Confess a funny habit you do when alone.",
        "Confess a song you secretly love but are embarrassed to admit.",
        "Say a cheesy pick-up line to someone in the group.",
        "Confess a weird fear you have.",
        "Say the funniest thing that has ever happened to you at school/work.",
        "Confess an embarrassing moment from your childhood.",
        "Say the weirdest dream you’ve ever had.",
        "Confess a food combination you secretly love but others might find gross.",
        "Say a ridiculous secret you’ve never told anyone.",
        "Confess the most childish thing you still do.",
        "Say the funniest nickname someone gave you.",
        "Confess a time you laughed at the wrong moment.",
        "Say a silly dare you wish someone would give you.",
        "Confess the most awkward situation you’ve been in with a crush.",
        "Say the funniest thing you’ve said while half-asleep.",
        "Confess a harmless lie you’ve told to get out of trouble.",
        "Say a funny misheard song lyric you believed for a long time.",
        "Confess a secret talent that no one knows about.",
        "Say a silly fear you had as a kid.",
        "Confess the weirdest thing you’ve eaten and liked.",
        "Say a funny joke or pun you just made up.",
        "Confess a movie or show you’re embarrassed to admit you love.",
        "Say a funny line pretending to be your future self.",
        "Confess the weirdest text message you’ve ever sent by mistake.",
        "Say a silly exaggeration about yourself.",
        "Confess a time you were caught doing something ridiculous.",
        "Say the funniest thing you’ve ever done in public.",
        "Confess a ridiculous superstition you follow.",
        "Say a funny story about a pet or animal encounter.",
        "Confess a time you misunderstood something hilariously.",
        "Say a cheesy line you would use to impress someone.",
        "Confess the silliest dare you’ve ever completed.",
        "Say a funny prediction about someone in the group.",
        "Confess the weirdest habit you have in the shower.",
        "Say the most ridiculous excuse you’ve ever used.",
        "Confess a time you embarrassed yourself trying to look cool.",
        "Say a funny compliment to someone in the group.",
        "Confess your love to the last snack you ate in a dramatic monologue.",
        "Admit the most embarrassing thing you’ve ever done to get out of a social event.",
        "Share the weirdest dream you’ve ever had as if it’s a real story.",
        "Confess a totally made-up crime and try to convince everyone it’s true.",
        "Say 'I’ve always secretly believed I’m royalty' with a straight face.",
        "Admit the silliest thing you’re secretly afraid of.",
        "Share your most embarrassing childhood nickname and the story behind it.",
        "Confess which cartoon character you had a crush on as a kid.",
        "Admit the stupidest way you’ve ever injured yourself.",
        "Say 'I still don’t know how to fold a fitted sheet' like it’s a deep secret.",
        "Confess the most ridiculous thing you’ve ever cried over.",
        "Admit which celebrity you’d ditch your current life for in a heartbeat.",
        "Share the strangest thing you’ve ever Googled at 2 AM.",
        "Confess your guilt over a petty 'crime' like stealing someone’s fries.",
        "Admit the worst gift you’ve ever regifted to someone else.",
        "Say 'I sometimes talk to inanimate objects and expect answers' like it’s normal.",
        "Confess which household chore you pretend to do to avoid real work.",
        "Admit the most childish thing you still do when no one’s watching.",
        "Share the most absurd lie you told as a kid that you thought was believable.",
        "Confess your secret talent that’s actually useless but you’re proud of.",
        "Admit which food you eat in a weird way (e.g., pizza crust first).",
        "Say 'I’ve definitely pretended to know a word I didn’t' with exaggerated shame.",
        "Confess the most embarrassing song on your secret playlist.",
        "Admit the dumbest thing you’ve ever argued about with full seriousness.",
        "Share the most ridiculous thing you’ve ever blamed on a pet or sibling.",
        "Confess your worst habit using Shakespearean language.",
        "Admit which movie you’ve never seen but pretend you have.",
        "Say 'I still can’t adult properly' as if it’s a shocking revelation.",
        "Confess the strangest thing you’ve ever stolen (e.g., a ketchup packet).",
        "Admit the most dramatic thing you’ve ever done over minor inconvenience.",
        "Share the silliest rumor you’ve ever started or believed.",
        "Confess your guilt over secretly judging someone’s life choices.",
        "Admit which 'basic' thing you secretly enjoy (e.g., pumpkin spice lattes).",
        "Say 'I’ve definitely eaten food off the floor' like it’s a dark confession.",
        "Confess the most embarrassing thing you’ve done for attention.",
        "Admit the worst fashion phase you went through and loved.",
        "Share the dumbest thing you’ve ever said with total confidence.",
        "Confess your most irrational pet peeve as if it’s a serious issue.",
        "Admit which board game you cheat at and how.",
        "Say 'I still don’t know all the words to the national anthem' dramatically."

    )
    val AdultD = listOf(
            "Describe your first kiss in detail.",
            "Give a playful dance to the person on your right without touching each other.",
            "Close your eyes and swipe right on a dating app 12 times.",
            "Make out with a pillow for 15 seconds, seriously.",
            "Share your most embarrassing bedroom moment that you haven't told before.",
            "Send a peach or eggplant emoji to the first contact in your phone.",
            "Perform a pole dance, real pole optional.",
            "Swap shirts with someone in the room.",
            "Dance in a funny or seductive way to 'I'm Too Sexy'.",
            "Give someone a one-minute head massage.",
            "Give someone a one-minute back massage.",
            "Ask someone to post a suggestive social media status for you.",
            "Give someone a one-minute massage on their lower back or butt.",
            "Kiss someone's favorite body part of the opposite gender.",
            "Let someone manage your dating profile for 10 minutes.",
            "Play a sexy song and dance against a chair for 30 seconds.",
            "Enter a hot tub or shower with your clothes on.",
            "Have someone post an embarrassing photo of you online.",
            "Take off your shirt for the rest of the game.",
            "Call your partner's parents and declare your love while funny sounds play.",
            "Have someone tickle you for 15 seconds.",
            "Eat a banana playfully while making eye contact with the person on your left.",
            "Close your eyes, take a random shot poured by someone, and sit on their lap.",
            "Pick an object and demonstrate how to use protection with it.",
            "Put ice cubes in your pants.",
            "Spin a bottle and kiss whoever it points to.",
            "Reenact your first sexual experience in a funny way.",
            "Read aloud a sex scene from a book dramatically.",
            "Imitate a sexy scene involving a fireman at a party.",
            "Feed someone grapes using only your mouth.",
            "Have someone draw a tattoo on your body with a marker.",
            "Do a body shot with someone (consent needed).",
            "Try to flirt with someone using only your voice.",
            "Hold an ice cube in your teeth and trace it on someone (with consent).",
            "Perform a striptease for the group.",
            "Lick chocolate or whipped cream off someone (with consent).",
            "Give a full-body massage to someone.",
            "Do sit-ups while kissing the person holding your legs.",
            "Lick someone's neck without touching them otherwise.",
            "Show someone your favorite sex position (demonstration).",
            "Keep your hand on the inner thigh of the person next to you until the next round.",
            "Pick the most boring person in the room and kiss them.",
            "Tell someone a naughty story using a seductive voice.",
            "Trace fingers on someone's lips and say 'just a silly boy' seductively.",
            "Go skinny dipping if there's a pool or beach nearby.",
            "Turn off lights and try to turn on the person to your right using only your voice.",
            "Call a random contact and leave a dirty voicemail.",
            "Leave an R-rated voicemail for an ex and delete their number.",
            "Post a suggestive social media status like 'Feeling horny…'.",
            "Play 'Seven Minutes in Heaven' with the person next to you."


    )
    val random =listOf(
        "Give someone a 5-second cheek kiss (consent required).",
        "Whisper a flirty secret to your crush.",
        "Send a playful flirty text to someone in the group.",
        "Do a slow-motion flirtatious walk across the room.",
        "Give someone a playful shoulder touch.",
        "Act like you’re on a romantic date for 30 seconds.",
        "Blow a kiss to someone across the room.",
        "Send a heart emoji to someone you like.",
        "Do a dramatic hair flip while winking at someone.",
        "Give someone a cheeky nudge with a smile.",
        "Whisper a teasing compliment to your crush.",
        "Do a 10-second slow-motion dance with someone.",
        "Act like a romantic movie lead for 15 seconds.",
        "Send a flirty GIF to someone nearby.",
        "Give someone a playful hand-hold (consent required).",
        "Do a dramatic slow-motion swoon for 10 seconds.",
        "Act like you’re receiving flowers from a secret admirer.",
        "Send a teasing sticker to someone you like.",
        "Do a playful 5-second wink and smile.",
        "Whisper a flirty joke to someone in the group.",
        "Perform a dramatic romantic gesture towards a crush.",
        "Give a playful back massage for 10 seconds (consent required).",
        "Act like you’re proposing dramatically to someone.",
        "Do a slow-motion dramatic kiss gesture to the air.",
        "Send a flirty emoji to the last person you texted.",
        "Give someone a cheeky playful poke or nudge.",
        "Do a dramatic romantic sigh for 10 seconds.",
        "Act like a soap opera character confessing love.",
        "Send a teasing message to a crush or partner.",
        "Do a playful eyebrow wiggle at someone nearby.",
        "Whisper a funny flirty line to someone you like.",
        "Act like you’re dancing seductively for 10 seconds.",
        "Give someone a playful hand-on-shoulder gesture.",
        "Do a dramatic swoon while looking at someone.",
        "Send a playful heart emoji to your crush.",
        "Act like you’re in a romantic movie scene with air.",
        "Do a funny dramatic flirty pose for 10 seconds.",
        "Give someone a cheeky wink and point.",
        "Send a flirty sticker or GIF to someone in the group.",
        "Do a slow-motion romantic walk across the room.",
        "Act like you’re receiving a love confession for 15 seconds.",
        "Whisper a teasing compliment to your partner or crush.",
        "Give a playful nudge or shoulder brush to someone.",
        "Do a dramatic hair toss and wink at someone nearby.",
        "Send a flirty emoji sequence to someone you like.",
        "Act like a character in a steamy romantic scene for 15 seconds.",
        "Do a playful slow-motion sway while making eye contact.",
        "Give someone a fun cheek tap or poke (consent required).",
        "Send a teasing text about something silly/flirty.",
        "Act like you’re proposing to an imaginary crush.",
        "Do a 10-second playful dance with a partner or object.",
        "Whisper a silly romantic confession to someone nearby.",
        "Give a cheeky high-five with a flirty smile.",
        "Do a dramatic slow-motion bow with eye contact.",
        "Act like a celebrity flirting with a fan for 15 seconds.",
        "Send a playful flirty GIF to someone in the group.",
        "Do a slow-motion flirty walk and spin around.",
        "Give someone a playful shoulder or arm touch.",
        "Whisper a flirty joke or pick-up line to a crush.",
        "Act like you’re receiving a love letter for 10 seconds.",
        "Do a 10-second playful slow-motion dance with air.",
        "Send a heart emoji or sticker to a crush or partner.",
        "Give someone a cheeky wink with a smile.",
        "Act like a romantic soap opera character for 15 seconds.",
        "Do a dramatic romantic gesture toward someone nearby.",
        "Whisper a teasing compliment to a crush or partner.",
        "Give a playful hand-hold for 5 seconds (consent required).",
        "Do a dramatic swoon pretending someone just confessed love.",
        "Send a flirty text to a random person in the group.",
        "Act like you’re dancing seductively with a chair or object.",
        "Do a slow-motion romantic walk around the room.",
        "Give someone a playful poke or nudge with a wink.",
        "Whisper a funny flirty secret to someone.",
        "Send a playful heart sticker to someone you like.",
        "Act like a romantic lead receiving flowers for 10 seconds.",
        "Do a 10-second dramatic romantic pose with eye contact.",
        "Give someone a cheeky shoulder brush or tap.",
        "Send a teasing message to a crush or partner.",
        "Do a playful eyebrow raise at someone nearby.",
        "Whisper a silly romantic confession to someone.",
        "Act like a character in a funny romantic movie scene.",
        "Do a dramatic hair flip and wink for 10 seconds.",
        "Give someone a playful nudge with a smile.",
        "Send a flirty emoji to a crush or friend.",
        "Act like you’re receiving a secret admirer note for 10 seconds.",
        "Do a slow-motion dramatic flirty walk across the room.",
        "Give someone a cheeky playful poke or high-five.",
        "Whisper a teasing compliment to someone near you.",
        "Send a playful flirty GIF to someone nearby.",
        "Act like you’re proposing in a funny dramatic way.",
        "Do a dramatic romantic sigh while looking at someone.",
        "Give someone a playful back massage for 10 seconds (consent required).",
        "Do a playful slow-motion dance with a partner or object.",
        "Whisper a flirty line to someone you like in 5 seconds.",
        "Send a teasing sticker or emoji to a crush or partner.",
        "Act like a celebrity flirting for 10 seconds.",
        "Do a playful wink and dramatic hair flip for 10 seconds.",
        "Give someone a cheeky nudge or shoulder tap.",
        "Send a heart emoji to someone nearby.",
        "Act like a romantic lead swooning for someone for 10 seconds.",
        "Do a dramatic 10-second slow-motion romantic pose.",
        "Whisper a funny flirty compliment to a crush or partner.",
        "Give someone a playful hand-on-shoulder gesture.",
        "Do a slow-motion flirty walk and spin with a smile.",
        "Send a teasing message or sticker to someone in the group.",
        "Act like you’re dancing seductively in slow motion.",
        "Do a 10-second dramatic romantic swoon for someone.",
        "Give a cheeky wink and playful smile to someone nearby.",
        "Whisper a silly flirty confession to someone.",
        "Send a playful heart emoji or GIF to a crush or partner.",
        "Act like a romantic movie character for 15 seconds.",
        "Do a dramatic hair flip and pose playfully for someone.",
        "Give someone a playful poke, nudge, or shoulder tap.",
        "Give someone a compliment in a funny way.",
        "Say three nice things about the person on your right.",
        "Praise the person across from you for something small.",
        "Give someone a creative nickname for 1 minute.",
        "Draw a silly face on your hand and show it to the group.",
        "Sing a line from a random song loudly.",
        "Dance for 30 seconds without music.",
        "Draw an object blindfolded and let others guess.",
        "Try a weird food combination chosen by the group.",
        "Lick something sour and describe the taste dramatically.",
        "Eat a spoonful of something spicy without flinching.",
        "Take a small bite of something unusual.",
        "Perform a group cheer in a funny way.",
        "Play charades with one hand behind your back.",
        "Form a human pyramid with the group.",
        "Pass a silly object around while acting serious.",
        "Run across the room pretending to be slow-motion.",
        "Do 10 jumping jacks in a funny style.",
        "Balance a book on your head for 30 seconds.",
        "Do 5 push-ups with dramatic sound effects.",
        "Walk across the room like a zombie.",
        "Pretend to be a superhero saving someone.",
        "Act like a villain plotting against the group.",
        "Imitate a celebrity for 1 minute.",
        "Do a robot dance for 20 seconds.",
        "Perform a dramatic movie scene chosen by the group.",
        "Wear a hat in the silliest way possible.",
        "Draw a funny mustache on your face.",
        "Wear socks on your hands for 5 minutes.",
        "Apply lipstick in a crazy color and show it.",
        "Put on two different shoes and walk around.",
        "Put on sunglasses indoors for 10 minutes.",
        "Apply blush in a funny pattern on your face.",
        "Whisper a funny secret to the person next to you.",
        "Do a dramatic hair flip for 10 seconds.",
        "Blow a kiss to someone across the room.",
        "Send a flirty emoji to a friend in the group.",
        "Do a slow-motion wink and smile at someone.",
        "Act like a romantic lead in a movie for 30 seconds.",
        "Give someone a playful shoulder massage for 10 seconds.",
        "Perform a silly dance for 20 seconds with someone.",
        "Imitate an animal of your choice for 30 seconds.",
        "Do a dramatic superhero landing.",
        "Act like a ghost trying to scare someone.",
        "Balance on one leg while hopping and clapping.",
        "Do a funny slow-motion fall to the floor.",
        "Make up a silly song and sing it for 15 seconds.",
        "Perform a short sketch using only gestures.",
        "Talk in a funny accent for the next 2 minutes.",
        "Do a dramatic reading of a silly sentence.",
        "Act like a news reporter in a disaster.",
        "Draw shapes on your face with makeup or eyeliner.",
        "Use a scarf as a cape and strike a superhero pose.",
        "Put on a wig and act like a celebrity.",
        "Perform a short puppet show using socks on your hands.",
        "Do a silly runway walk with exaggerated gestures.",
        "Act like an alien discovering Earth for 30 seconds.",
        "Make the group laugh with a funny face for 10 seconds.",
        "Do 10 squats while singing a random song.",
        "Hop across the room like a frog.",
        "Spin in a circle 5 times and walk straight.",
        "Act like a chef presenting a fancy invisible dish.",
        "Do a dramatic slow-motion sneeze.",
        "Give a dramatic performance of a romantic scene.",
        "Talk like a robot for the next 2 minutes.",
        "Perform a short comedy sketch chosen by the group.",
        "Act like a pirate searching for treasure on the floor.",
        "Give someone a cheeky wink and smile.",
        "Send a flirty sticker or GIF to a friend.",
        "Do a 10-second dramatic swoon over someone.",
        "Perform a slow-motion dance with a chair or object.",
        "Whisper a funny flirty line to someone nearby.",
        "Do a playful eyebrow wiggle at someone.",
        "Act like you’re getting flowers from a secret admirer.",
        "Give someone a playful poke or nudge.",
        "Do a dramatic hair toss and wink.",
        "Send a cheeky heart emoji to someone.",
        "Pretend to faint dramatically from love or flirting.",
        "Give someone a playful hand-hold (consent required).",
        "Perform a silly imitation of someone in the group.",
        "Act like a romantic lead proposing dramatically.",
        "Do a slow-motion dramatic walk towards someone.",
        "Give a playful back massage to someone (consent required).",
        "Send a teasing message to someone in the group.",
        "Act like you’re dancing seductively with air.",
        "Do a playful slow-motion wink and smile at someone.",
        "Blow a funny kiss to an imaginary crush.",
        "Perform a dramatic slow-motion fall as if tripping.",
        "Act like a romantic movie character for 15 seconds.",
        "Do a 10-second playful dance with your eyes closed.",
        "Say a flirty pickup line in a silly voice.",
        "Perform a dramatic entrance into the room.",
        "Do a funny impression of a cartoon character.",
        "Act like a superhero saving the world dramatically.",
        "Do 10 push-ups while making funny sound effects.",
        "Balance a book on your head and walk across the room.",
        "Spin around 5 times and try to walk straight.",
        "Act like a villain plotting a silly plan.",
        "Do a dramatic slow-motion jump into the air.",
        "Perform a silly walk around the group.",
        "Say a funny line in a dramatic Shakespeare style.",
        "Do a 10-second dance like no one is watching.",
        "Pretend to be a cat reacting to a cucumber.",
        "Imitate a dog begging for a treat.",
        "Do a funny impression of a famous celebrity.",
        "Act like a zombie running from danger.",
        "Perform a short romantic scene with a chair.",
        "Give someone a dramatic, playful compliment.",
        "Do a funny runway walk across the room.",
        "Act like a ghost floating dramatically.",
        "Perform a silly dramatic fall to the floor.",
        "Give someone a cheeky wink and a smile.",
        "Send a playful emoji to the last person you texted.",
        "Perform a 10-second dramatic romantic pose.",
        "Do a playful 10-second slow-motion dance.",
        "Whisper a funny secret to someone nearby.",
        "Act like a news reporter in a dramatic scene.",
        "Draw a funny face on your arm with eyeliner.",
        "Do 5 squats while making a funny noise.",
        "Hop across the room like a kangaroo.",
        "Spin in a circle 5 times and bow to the group.",
        "Act like a pirate discovering treasure.",
        "Perform a silly slow-motion superhero landing.",
        "Give someone a playful shoulder brush.",
        "Act like you’re receiving a bouquet from a secret admirer.",
        "Do a dramatic hair flip and pose.",
        "Send a flirty sticker to someone in the group.",
        "Do a playful slow-motion swoon towards someone.",
        "Act like a romantic movie scene is happening.",
        "Perform a funny dance with an imaginary partner.",
        "Give someone a cheeky nudge and wink.",
        "Do a 10-second dramatic eye roll and sigh.",
        "Whisper a silly line to someone nearby.",
        "Act like a character in a steamy romance scene.",
        "Perform a short puppet show with socks or hands.",
        "Do a silly dramatic bow to the group.",
        "Balance on one foot and spin slowly for 10 seconds.",
        "Act like you’re a celebrity walking a red carpet.",
        "Do a 10-second dramatic slow-motion jump.",
        "Send a flirty emoji to a friend or crush.",
        "Act like you’re receiving a love confession.",
        "Do a playful wink and cheeky smile for 10 seconds.",
        "Give someone a playful hand-hold or shoulder touch.",
        "Perform a silly slow-motion dance move.",
        "Do a dramatic swoon for 10 seconds.",
        "Whisper a flirty joke or compliment to someone.",
        "Act like a superhero landing dramatically.",
        "Perform a silly impression of someone famous.",
        "Do 10 jumping jacks while singing a random song.",
        "Balance a book on your head and walk slowly.",
        "Act like a ghost floating across the room.",
        "Do a dramatic slow-motion fall and get up theatrically.",
        "Perform a funny impression of a cartoon character.",
        "Give someone a playful shoulder poke.",
        "Do a dramatic hair toss and wink at someone.",
        "Act like a romantic lead receiving flowers.",
        "Send a flirty GIF to someone in the group.",
        "Do a playful eyebrow wiggle at someone nearby.",
        "Act like you’re dancing seductively with a chair.",
        "Give a cheeky playful nudge or high-five.",
        "Do a funny dramatic face for 10 seconds.",
        "Perform a short comedy sketch with gestures.",
        "Act like an alien discovering Earth for 30 seconds.",
        "Do a 10-second dramatic flirty gaze.",
        "Send a playful teasing message to a friend.",
        "Act like a romantic lead proposing dramatically.",
        "Perform a slow-motion dramatic walk across the room.",
        "Give a playful back massage to someone (consent needed).",
        "Do a 10-second slow dance with an imaginary partner.",
        "Act like you’re receiving a secret admirer note.",
        "Send a flirty emoji or sticker to a friend.",
        "Perform a dramatic superhero landing for 10 seconds.",
        "Do a playful slow-motion wink and smile at someone.",
        "Blow a kiss to someone across the room dramatically.",
        "Perform a silly dance with air for 15 seconds.",
        "Act like you’re in a romantic movie scene for 20 seconds.",
        "Do a dramatic hair flip and pose playfully.",
        "Give someone a cheeky wink and smile.",
        "Send a flirty heart emoji to someone nearby.",
        "Do a playful slow-motion swoon for 10 seconds.",
        "Act like you’re proposing in a funny dramatic way.",
        "Do a 10-second playful dance with your eyes closed.",
        "Say a funny flirty pickup line to someone.",
        "Perform a dramatic entrance into the room playfully.",
        "Do a silly impression of a famous celebrity for 15 seconds.",
        "Act like a villain plotting a playful scheme.",
        "Do a dramatic slow-motion jump and land theatrically."
    )
    val dareMap: Map<String, List<String>> = mapOf(
        "Compliments" to Compliments,
        "Creative" to Creative,
        "AdultD" to AdultD,
        "Food" to Food,
        "Group" to Group,
        "Mystery" to Mystery,
        "Pranks" to Pranks,
        "Silly" to Silly,
        "SocialMedia" to SocialMedia,
        "Tech" to Tech,
        "TimeGames" to TimeGames,
        "Acting" to Acting,
        "Confessions" to Confessions,
        "Random" to random
    )
    fun getDare(dare: String): List<String>? = dareMap[dare]
}
