package com.example.tnd.model
class TruthData {
    val Deep = listOf(
        "What moment changed your life the most?",
        "What hard lesson have you learned?",
        "When do you feel most like yourself?",
        "If you could relive one day, which would it be?",
        "What small habit would you like to start or quit?",
        "What do people often misunderstand about you?",
        "What boundary is hardest for you to keep?",
        "What would you tell your younger self?",
        "When do you feel most loved?",
        "What’s the kindest thing someone has done for you?",
        "What compliment would make you happiest to hear?",
        "Have you lost touch with someone you still miss?",
        "Who has taught you the most about life?",
        "How do you show people you care about them?",
        "What scares you about sharing your feelings?",
        "If you knew you couldn’t fail, what dream would you try?",
        "What risk do you want to take?",
        "How do you hope people see you when you’re older?",
        "What goal have you been putting off?",
        "What do you want your life to look like in ten years?",
        "What value or rule guides your choices?",
        "What belief have you changed your mind about?",
        "If you could learn the truth about one big mystery, what would it be?",
        "What makes life special for you?",
        "Do you think people can really change? Why?",
        "If your life was a book, what would this chapter be called and what’s next?",
        "What dream have you let go of, and why?",
        "How would you describe yourself to someone new?",
        "What failure still makes you sad, and what did you learn?",
        "What worries you most about getting older?",
        "What compliment is hard for you to believe, and why?",
        "When did you last feel like you didn’t belong, and how did you handle it?",
        "What part of yourself are you scared to show others?",
        "What lesson about love did you learn the hard way?",
        "What does unconditional love mean to you? Do you think it’s real?",
        "What advice about relationships would you give your younger self?",
        "When did someone last change how you see something important?",
        "What boundary has helped you have better relationships?",
        "What small choice from your past changed your life a lot?",
        "What do you hope people say about you after you’re gone?",
        "If you could leave one sentence of advice for future people, what would it be?",
        "What happy memory helps you feel calm?",
        "If you could know one honest truth about yourself, what would it be?",
        "If there was a museum about your life, what would be in the center?",
        "What big question about life or yourself do you still wonder about?",
        "How have you made a big difference in someone’s life?",
        "What is one thing you wish you could tell your future self?",
        "What choice are you proud of but never shared?",
        "If you could relive one simple moment in your life, what would it be?",
        "What fear have you faced that made you stronger?",
        "Who has influenced you most, and how?",
        "What are you most grateful for right now?"
    )

    val Embarrassing = listOf(
        "What’s the most embarrassing thing you’ve ever done in public?",
        "Have you ever tripped or slipped in front of a lot of people (or someone you liked)?",
        "Have you ever fallen asleep somewhere really awkward?",
        "What’s the most embarrassing accident you’ve had in public?",
        "Have you ever walked into the wrong bathroom or room?",
        "What’s the most embarrassing thing that happened at school or work?",
        "What’s the most embarrassing thing that happened at a family party or event?",
        "What’s the most awkward text or message you’ve sent by mistake?",
        "Have you ever sent a selfie or photo to the wrong person?",
        "Have you ever texted or posted something you wish you could take back?",
        "Have you ever sent a message complaining about someone to that same person?",
        "What’s the most awkward thing you’ve done on social media?",
        "Have you ever said something awkward to a crush or partner?",
        "What’s the most embarrassing thing you’ve done in front of a crush?",
        "What’s the funniest or most embarrassing thing that happened on a date?",
        "Have you ever had an awkward first kiss or hug?",
        "Have you ever tried to impress someone and totally failed?",
        "Have you ever called someone by the wrong name?",
        "Have you ever forgotten someone’s name right after they told you?",
        "Have you ever been caught talking to yourself?",
        "Have you ever gotten caught staring at someone?",
        "What’s the silliest thing you’ve done to get attention?",
        "What’s the weirdest or funniest sound you’ve made by accident?",
        "Have you ever misheard someone and answered in a weird way?",
        "What’s the funniest misunderstanding you’ve been part of?",
        "Have you ever laughed at the wrong moment and felt embarrassed?",
        "Have you ever forgotten your lines or words while speaking or performing?",
        "What’s your worst wardrobe malfunction ever?",
        "Have you ever had food stuck in your teeth or something on your face without knowing?",
        "What’s the most embarrassing thing you’ve done while trying to look cool?",
        "What’s the most embarrassing thing you’ve done in a group photo?",
        "What’s the most embarrassing nickname you’ve had?",
        "Have you ever been caught singing or dancing when you thought nobody was watching?",
        "What’s the most awkward thing that’s happened on a video call?",
        "What’s the most embarrassing thing that’s happened while singing, acting, or performing?",
        "Have you ever forgotten to mute yourself and said something awkward?",
        "What’s the most embarrassing dream you’ve ever shared?"
    )

    val Favorites = listOf(
        "What is your favorite color?",
        "What is your favorite food?",
        "What is your favorite drink?",
        "What is your favorite childhood memory?",
        "What is your favorite memory with friends?",
        "What is your favorite memory with your family?",
        "What is your favorite memory from high school?",
        "What is your favorite childhood game?",
        "What is your favorite childhood cartoon or TV show?",
        "What is your favorite movie of all time?",
        "What is your favorite movie to watch when you need a good laugh?",
        "What is your favorite song or piece of music?",
        "What is your favorite song from your teenage years?",
        "What is your favorite song you never get tired of?",
        "What is your favorite book or story?",
        "What is your favorite book you’ve ever read?",
        "What is your favorite hobby or activity?",
        "What is your favorite hobby you’ve always wanted to try?",
        "What is your favorite way to relax after a long or stressful day?",
        "What is your favorite way to spend a weekend?",
        "What is your favorite way to spend a lazy Sunday?",
        "What is your favorite holiday or celebration?",
        "What is your favorite holiday and how do you like to celebrate it?",
        "What is your favorite family tradition?",
        "What is your favorite comfort food and why?",
        "What is your favorite food you could eat every day?",
        "What is your favorite snack or treat?",
        "What is your favorite dessert?",
        "What is your favorite type of dessert?",
        "What is your favorite drink?",
        "What is your favorite meal that someone else cooks for you?",
        "What is your favorite thing to cook or bake?",
        "What is your favorite place you’ve ever visited?",
        "What is your favorite place to go when you need peace?",
        "What is your favorite thing about yourself?",
        "What is your favorite thing about your personality?",
        "What is your favorite thing about your best friend?",
        "What is your favorite quality in a friend?",
        "What is your favorite quality in a partner?",
        "What is your favorite gift you’ve ever received?",
        "What is your favorite thing you own?",
        "What is your favorite thing about your home or room?",
        "What is your favorite outfit or piece of clothing?",
        "What is your favorite thing to do outdoors?",
        "What is your favorite way to exercise or stay active?",
        "What is your favorite thing to do on a date?",
        "What is your favorite activity to do with family?",
        "What is your favorite activity to do with friends?",
        "What is your favorite way to help someone?",
        "What is your favorite time of day?",
        "What is your favorite season of the year?",
        "What is your favorite season and what do you love most about it?",
        "What is your favorite type of weather?",
        "What is your favorite sport to watch or play?",
        "What is your favorite animal?",
        "What is your favorite subject in school or topic to learn?",
        "What is your favorite app or website?",
        "What is your favorite app on your phone?",
        "What is your favorite smell?",
        "What is your favorite smell in the world?",
        "What is your favorite sound?",
        "What is your favorite color and why?",
        "What is your favorite random fact you know?",
        "What is your favorite quote or saying?",
        "What is your favorite simple pleasure in life?",
        "Who is your favorite person to spend time with?",
        "What is your favorite thing to do when you are alone?",
        "What is your favorite thing to do when you’re alone?",
        "What is your favorite memory with our friend group?"


    )

    val Friendship = listOf(
            "Who is your oldest friend and how did you meet?",
            "What is your favorite memory with a friend?",
            "Who do you trust the most and why?",
            "Have you ever had a big fight with a friend? What happened?",
            "Who has made the biggest difference in your life?",
            "Have you ever had a friendship turn into something more?",
            "What makes someone a true friend to you?",
            "Who do you talk to when you need advice?",
            "Have you ever lost a close friend? How did it happen?",
            "What is one thing you really value in a friend?",
            "Who was your first crush?",
            "Have you ever been jealous of a friend? Why?",
            "What is the best thing a friend has ever done for you?",
            "Who knows you better than anyone else?",
            "Have you ever kept a secret from a friend? Why?",
            "What is the kindest thing you have done for a friend?",
            "What is the hardest part about keeping friendships?",
            "Have you ever made up after a long fight? How?",
            "Who do you miss the most right now?",
            "What makes you feel loved in a friendship?",
            "Have you ever had to set a boundary with a friend or partner?",
            "What is the most romantic thing someone has done for you?",
            "Who was your first real love?",
            "Have you ever been heartbroken? What helped you heal?",
            "What is something you look for in a partner?",
            "What is your favorite thing to do with someone you care about?",
            "Have you ever surprised someone you love? What did you do?",
            "Who makes you laugh the most?",
            "What is the most important lesson you have learned about love?",
            "Have you ever helped a friend through a hard time?",
            "Have you ever had to forgive someone you care about?",
            "Who is the one person you can always count on?",
            "What is your love language or how do you show you care?",
            "Have you ever been scared to tell someone how you felt?",
            "What is one quality you admire in a friend or partner?",
            "What is the best relationship advice you have heard?",
            "What makes you feel most connected to someone?",
            "Have you ever done something embarrassing for someone you liked?",
            "Who has taught you the most about friendship?",
            "Have you ever felt left out by your friends? How did you deal with it?",
            "What do you think is the key to a strong relationship?",
            "What is your favorite way to spend time with close friends or a partner?",
            "Who do you want to grow closer to and why?",
            "What’s the first thing you noticed about me when we met?",
            "What’s your favorite memory of our friendship or relationship?",
            "What’s one thing you think I’m really good at?",
            "Have you ever been jealous of one of my other friendships?",
            "What’s one habit of mine that you find sweet?",
            "What’s one habit of mine that secretly annoys you?",
            "What’s the most valuable lesson you’ve learned from our relationship?",
            "When did you know we’d be close friends?",
            "What’s something you’ve wanted to tell me but haven’t?",
            "How has our friendship changed you for the better?",
            "What’s your favorite thing we do together?",
            "What’s a time I really disappointed you?",
            "What’s something you think I’m scared to tell you?",
            "What’s the nicest thing you’ve done for me that I don’t know about?",
            "How do we balance each other out?",
            "What relationship advice do you think I need?",
            "What’s your favorite thing about our friendship?",
            "What’s something you wish we did more often?",
            "What’s a secret you’ve kept from me?",
            "What’s one thing you think I misunderstand about you?",
            "What was the hardest time in our friendship?",
            "What’s something you’re proud of me for?",
            "What’s a boundary you wish I respected more?",
            "What’s one thing you’d change about our relationship?",
            "What’s our best inside joke?",
            "What’s something you’ve learned about yourself from our friendship?",
            "When did you feel most supported by me?",
            "What’s something you wish I’d ask you about?",
            "What’s the most important thing I should know about you?",
            "How has our friendship surprised you?"
    )

    val NeverHaveIEver = listOf(
        "Never have I ever ghosted someone.",
        "Never have I ever pretended to be sick to get out of plans.",
        "Never have I ever sung in the shower.",
        "Never have I ever sung karaoke in front of people.",
        "Never have I ever cried during a movie.",
        "Never have I ever laughed so hard I cried.",
        "Never have I ever laughed so hard I snorted.",
        "Never have I ever eaten food that fell on the floor.",
        "Never have I ever hidden snacks so I didn’t have to share.",
        "Never have I ever Googled my own name.",
        "Never have I ever had a crush on a teacher.",
        "Never have I ever snooped through someone else's phone.",
        "Never have I ever lied about my age.",
        "Never have I ever sent a text to the wrong person.",
        "Never have I ever accidentally sent a message to the wrong person.",
        "Never have I ever walked into a glass door or wall.",
        "Never have I ever tripped in public and played it off.",
        "Never have I ever worn mismatched socks all day without noticing.",
        "Never have I ever worn shoes on the wrong feet.",
        "Never have I ever worn clothes backward without realizing.",
        "Never have I ever worn pajamas all day.",
        "Never have I ever gone to bed without brushing my teeth.",
        "Never have I ever tried to talk to an animal in a human voice.",
        "Never have I ever gotten completely lost in a familiar place.",
        "Never have I ever waved at someone who wasn’t waving at me.",
        "Never have I ever accidentally liked an old photo on social media.",
        "Never have I ever argued with a GPS.",
        "Never have I ever mistaken a stranger for someone I know.",
        "Never have I ever forgotten where I parked my car or bike.",
        "Never have I ever lost my phone in my own home.",
        "Never have I ever broken something and blamed someone else.",
        "Never have I ever spilled a drink on myself in public.",
        "Never have I ever spilled food on myself during a date or meal.",
        "Never have I ever spilled something all over myself at a party.",
        "Never have I ever taken a silly photo I regretted later.",
        "Never have I ever texted someone while standing next to them.",
        "Never have I ever told a joke that nobody laughed at.",
        "Never have I ever tried to take a cool photo and failed.",
        "Never have I ever made up an excuse to get out of plans.",
        "Never have I ever stayed up all night watching movies or shows.",
        "Never have I ever fallen asleep in class or at work.",
        "Never have I ever fallen asleep in an awkward place, like on a bus or sofa.",
        "Never have I ever fallen asleep while watching a movie with friends.",
        "Never have I ever said the wrong name by mistake.",
        "Never have I ever pretended to understand something when I didn’t.",
        "Never have I ever forgotten an important date like a birthday.",
        "Never have I ever eaten an entire pizza by myself.",
        "Never have I ever dropped my phone in an awkward place.",
        "Never have I ever dreamed I was back in school without pants.",
        "Never have I ever had a secret crush on a friend.",
        "Never have I ever stalked an ex on social media.",
        "Never have I ever fallen in love at first sight.",
        "Never have I ever written a love letter or poem.",
        "Never have I ever been on a blind date.",
        "Never have I ever had a dream about an ex.",
        "Never have I ever pretended to be busy to seem less available.",
        "Never have I ever kissed someone in the rain.",
        "Never have I ever had a romantic thought about a celebrity.",
        "Never have I ever said 'I love you' without meaning it.",
        "Never have I ever had a one-night stand.",
        "Never have I ever sent a nude photo.",
        "Never have I ever kissed a stranger.",
        "Never have I ever had a secret relationship.",
        "Never have I ever had a crush on a friend’s sibling.",
        "Never have I ever fantasized about someone in this room.",
        "Never have I ever gotten a tattoo or piercing in a private place.",
        "Never have I ever been caught in the act.",
        "Never have I ever had a romantic encounter in a public place.",
        "Never have I ever lied about my relationship status.",
        "Never have I ever been scared by a prank. What happened?"


    )

    val Secrets = listOf(
        "What's a secret you've never told anyone?",
        "What's something you're ashamed of that you've never admitted?",
        "What's a lie you've told that everyone believes?",
        "What's a fear you have that you think nobody would understand?",
        "What's a regret you still think about often?",
        "What's something you've stolen and never returned?",
        "What's a dream you've never shared because it seems too silly?",
        "What's a bad habit you hide from everyone?",
        "What's an embarrassing memory that still keeps you up at night?",
        "What's a piece of gossip you've never shared but want to?",
        "What's a time you betrayed someone's trust and got away with it?",
        "What's a selfish thing you've done that you're not proud of?",
        "What's a secret about your family you've never told friends?",
        "What's a password you still remember from someone else's account?",
        "What's something you pretend to like but actually hate?",
        "What's a time you cheated on a test or assignment and never got caught?",
        "What's a message or email you've written but never sent?",
        "What's a hidden talent or skill you've never shown anyone?",
        "What's a childhood secret you've never told your parents?",
        "What's a guilty pleasure you're embarrassed to enjoy?",
        "What's a time you let someone take the blame for something you did?",
        "What's an insecurity you hide from everyone?",
        "What's a rumor you've spread that wasn't true?",
        "What's a browser search you'd be embarrassed for people to see?",
        "What's a promise you broke and never confessed?",
        "What's a possession you have that you shouldn't?",
        "What's a compliment you've received but didn’t believe?",
        "What's a fear about yourself you've never voiced?",
        "What's a time you pretended to know something you didn't?",
        "What's a secret you kept to protect someone else?",
        "What is a small secret you’ve never told anyone?",
        "Have you ever kept a silly secret from your best friend?",
        "What is something you’ve done that nobody knows about?",
        "What is a funny thing you used to believe as a kid?",
        "Have you ever hidden a snack so no one else could find it?",
        "What is a secret talent you’ve never shown anyone?",
        "Have you ever made up an excuse to avoid plans?",
        "What is the silliest thing you’ve done alone?",
        "What is a small lie you once told to get out of trouble?",
        "Have you ever written something in a diary or journal that you’d never read out loud?",
        "What is something you love that most people wouldn’t guess?",
        "What is a secret nickname you’ve had or given someone?",
        "Have you ever pretended to like something you didn’t?",
        "What is the weirdest thing you’ve ever collected or saved?",
        "Have you ever had a secret hiding spot for special things?",
        "What is a song you secretly love but don’t admit to others?",
        "Have you ever laughed at something you shouldn’t have?",
        "What is a movie or show you secretly watch on repeat?",
        "Have you ever had a crush on someone and kept it secret?",
        "What is a food you secretly dislike but eat anyway?",
        "Have you ever sent a message you wish you could take back?",
        "What is the strangest thing you’ve done when you were bored?",
        "Have you ever kept a surprise and almost ruined it?",
        "What is a childhood habit you still secretly do?",
        "Have you ever bought something and kept it secret?",
        "What is a secret you’ve kept from your parents or family?",
        "Have you ever made up a story to make someone laugh?",
        "What is something small that you’re secretly proud of?",
        "Have you ever kept a secret for a friend that was hard to keep?",
        "What is a hobby or interest you don’t usually talk about?",
        "Have you ever hidden something embarrassing from your room or bag?",
        "What is a dream you’ve never told anyone?",
        "Have you ever tried something new and kept it a secret?",
        "What is something you’ve done that you’ll never tell your parents?",
        "Have you ever had a silly fear you didn’t share with anyone?",
        "What is a funny mistake you kept to yourself?",
        "Have you ever liked a song or artist people might laugh at?",
        "What is the most unusual thing you’ve ever kept?",
        "Have you ever had a secret about a gift or surprise you planned?",
        "What is a tiny goal you secretly hope to reach one day?",
        "Have you ever wanted to try something but been too shy to say?",
        "What is a secret about yourself that makes you smile?"



    )

    val Romantic = listOf(
        "Who was your first crush?",
        "Who was your first real love?",
        "What was your first impression of your partner or crush?",
        "What’s your favorite romantic movie or story?",
        "What’s your idea of a perfect date?",
        "Have you ever had a secret admirer?",
        "What’s the sweetest thing someone has ever done for you?",
        "What’s the most romantic gesture you’ve made for someone?",
        "What’s the biggest risk you’ve taken for love?",
        "What’s your favorite memory from a first date?",
        "What’s the most embarrassing thing that happened on a date?",
        "What’s the most thoughtful gift you’ve ever received?",
        "What’s your favorite way to spend time with someone you love?",
        "What’s your favorite romantic gesture?",
        "Have you ever written a love note, poem, or letter?",
        "Have you ever made a handmade gift for someone you cared about?",
        "What’s a simple way someone can win your heart?",
        "What’s a song that reminds you of someone you like?",
        "What’s a song you’d put on a love playlist?",
        "What’s a romantic movie scene that reflects what you want in real life?",
        "Have you ever surprised someone you cared about?",
        "Have you ever been surprised with flowers or a note?",
        "Have you ever shared an umbrella with someone special?",
        "Have you ever had a romantic moment in the rain?",
        "What’s a funny or awkward date story you’ve had?",
        "What’s your favorite memory with someone you liked?",
        "What’s the longest you’ve had a crush without telling them?",
        "What’s something you need to feel loved but are shy to ask for?",
        "What’s something you pretend to like in relationships but actually don’t?",
        "What’s a romantic fantasy you’ve never shared?",
        "What’s the most impulsive thing you’ve done for love?",
        "What’s the biggest misconception about your love life?",
        "What’s your biggest turn-on in a partner?",
        "What’s a deal-breaker for you that others might find unusual?",
        "What’s a small thing someone could do to make you feel special?",
        "What’s the nicest compliment you’ve received about your smile or laugh?",
        "What’s one quality you admire most in a partner?",
        "What’s the most attractive thing about someone beyond looks?",
        "What’s your biggest fear about commitment?",
        "What’s a relationship lesson you learned the hard way?",
        "What’s a relationship skill you’re proud of?",
        "What’s something about your approach to love that’s changed over time?",
        "What’s the best relationship advice you’ve heard?",
        "What’s a relationship milestone that makes you nervous?",
        "What’s the most unexpected place you’ve ever felt attracted to someone?",
        "What makes you feel most cared for in a relationship?",
        "Have you ever been too shy to talk to someone you liked?",
        "Have you ever kept a small gift from someone you liked?",
        "Have you ever made a playlist or mix for someone special?",
        "What’s your favorite thing about falling in love?",
        "What’s your favorite thing about a happy couple you know?",
        "What’s a little thing someone could do to cheer you up?",
        "What’s your favorite way to show someone you appreciate them?",
        "What’s a relationship boundary you’d never compromise on?"


    )

    val Spicy = listOf(
        "Have you ever kissed someone unexpectedly?",
            "How many sexual partners do you think is too many?",
            "Has anyone ever laughed at you during sex?",
            "Do you remember everyone you’ve slept with?",
            "How far would you go on a first date?",
            "What was your best kiss like?",
            "Have you ever had a fling with a coworker or boss?",
            "Who is the most inappropriate person you’ve fantasized about?",
            "If you saw your parents watching an adult movie, what would you do?",
            "What’s the sexiest gift you’ve ever given or received?",
            "When did you last go skinny dipping?",
            "What’s the sexiest thing someone not your partner has said to you?",
            "Do you think people can really stay faithful?",
            "What’s the biggest age difference with someone you’ve slept with?",
            "What’s the weirdest thing you’ve done on a first date?",
            "Have you ever sent a flirty or naughty text?",
            "Have you ever wanted someone you wouldn’t normally date?",
            "Do you think sex is better with love or just attraction?",
            "Have you ever sent a sexy picture by mistake?",
            "Have you ever kissed someone of the same sex as a joke?",
            "Describe the sexiest outfit you’ve owned.",
            "If you woke up as the opposite sex, what naughty things would you do?",
            "Do you own any adult toys?",
            "Which adult movie have you watched more than once?",
            "What’s your funniest or most embarrassing bedroom moment?",
            "What’s your least favorite sexual position?",
            "What do you remember about your first time having sex?",
            "Have you ever regretted sleeping with someone?",
            "Have you ever been with someone much older or younger than you?",
            "How often do you watch adult content?",
            "Describe your hottest dream.",
            "Have you ever kissed a family member as a joke?",
            "Have you had a same-sex experience or fantasy about a friend?",
            "When was your last one-night stand?",
            "When did you last touch yourself?",
            "Have you ever had sex before kissing?",
            "Have you ever dominated or been dominated by someone?",
            "Do you enjoy giving or receiving more?",
            "What’s the horniest you’ve ever felt?",
            "Have you ever hired an escort?",
            "Have you fantasized about someone of the same sex?",
            "Have you ever cheated on a partner?",
            "Would you choose romantic or passionate sex if you had to pick one?",
            "Have you tried being tied up or restrained?",
            "What was the last adult movie you watched?",
            "Who in this room would you most want to sleep with?",
            "If someone could tie you up and tease you, who would it be?",
            "Have you ever tried anal sex?",
            "If you could have a threesome with people in this room, who would you pick?",
            "Have you ever had a threesome?",
            "Have you ever made a private intimate video?",
            "What's the most daring place you've fantasized about being intimate?",
            "What's a body part that grabs your attention immediately?",
            "What's a secret turn-on you’ve never told anyone?",
            "What's the biggest lie you told to get out of a date?",
            "What's the sexiest message you’ve ever received?",
            "What's a word or phrase that instantly turns you on?",
            "What's the most embarrassing thing a partner has called you during sex?",
            "What's something you're surprisingly good at in bed?",
            "What's the worst pick-up line that actually worked on you?",
            "What's something you want to try in bed but haven’t suggested?",
            "What's your favorite adult toy or item?",
            "What's the biggest secret you’ve kept from a partner about your past?",
            "What's a movie or book scene that always excites you?",
            "What's the craziest thing you’ve done to avoid getting caught?",
            "What's a piece of clothing you find irresistible on someone?",
            "What's your go-to fantasy when you want to finish quickly?",
            "What's the best 'bad decision' you’ve made with someone?",
            "What's a secret you’d only tell someone in the dark?",
            "What's the biggest deal-breaker for you in bed?",
            "What's something you pretended to like for a partner?",
            "What's the most times you’ve been intimate in 24 hours?",
            "What's the funniest excuse you’ve used to leave a bad date?",
            "What's a place you’ve been intimate that you’re not proud of?",
            "What's the strangest thing you’ve used as a toy?",
            "What's a secret desire you’re too shy to act on?",
            "Who is the last person you stalked on social media?",
            "What's a sound that drives you wild?",
            "What's the biggest age gap you’ve had with a partner?",
            "What's a rule you said you’d never break but did?",
            "What's the most jealous you’ve ever been in a relationship?",
            "What's a guilty pleasure you’d never want friends to know about?",
            "What's the wildest thing you’ve done that you don’t regret?",
            "What's a hidden talent that could be useful in bed?",
            "What's the best thing you’ve learned from an ex?",
            "What's your favorite type of aftercare?",
            "What's a secret you hope your partner never finds out?",
            "What's the biggest misunderstanding you’ve had during a hookup?",
            "What's the most embarrassing thing you’ve had to explain to a new partner?",
            "What's a fantasy involving a stranger you’ve always had?",
            "What's the fastest you’ve gone from meeting someone to being intimate?",
            "What's a compliment you received that was meant to be sexy?",
            "What's something you find extremely hot that others might find weird?"

    )

    val Travel = listOf(
        "What’s the best trip you’ve ever been on?",
        "Which country or city is at the top of your travel bucket list?",
        "Have you ever traveled alone? How was it?",
        "What’s the most adventurous thing you’ve done while traveling?",
        "Have you ever gotten lost in a foreign place?",
        "What’s your favorite way to travel — plane, train, car, or boat?",
        "Have you ever tried a food you couldn’t pronounce while traveling?",
        "What’s the scariest thing that has happened to you on a trip?",
        "Have you ever made friends with strangers while traveling?",
        "What’s the most beautiful place you’ve ever visited?",
        "Have you ever gone on a spontaneous road trip?",
        "What’s the funniest travel mishap you’ve experienced?",
        "Have you ever stayed in a really unusual place while traveling?",
        "What’s your dream adventure activity (like skydiving, scuba diving, or bungee jumping)?",
        "Have you ever missed a flight, train, or bus while traveling?",
        "What’s the most unique souvenir you’ve ever brought home?",
        "Have you ever tried camping or sleeping outdoors on a trip?",
        "What’s the longest trip you’ve ever taken?",
        "Have you ever had a travel plan completely ruined? What happened?",
        "What’s your favorite memory from a beach or mountain trip?",
        "Have you ever gotten lost in nature, like a forest or mountain?",
        "What’s the most fun city you’ve explored?",
        "Have you ever traveled to a place just for food or festivals?",
        "What’s a travel experience that totally scared you?",
        "Have you ever met someone famous while traveling?",
        "What’s the most unusual mode of transportation you’ve used on a trip?",
        "Have you ever taken a trip without planning at all?",
        "What’s the strangest thing you’ve seen while traveling?",
        "Have you ever gone on a trip that changed your perspective on life?",
        "What’s the best adventure you’ve had with friends?",
        "Have you ever had a travel experience that turned into a funny story?",
        "What’s your dream country to visit next?",
        "Have you ever faced a language barrier while traveling?",
        "What’s the best meal you’ve had while traveling?",
        "Have you ever been on a trip that felt dangerous but exciting?",
        "What’s your favorite season or time of year to travel?",
        "Have you ever gone on a trip just for relaxation?",
        "What’s the most unforgettable sunset or sunrise you’ve seen?",
        "Have you ever taken a photo you’re really proud of while traveling?",
        "What’s the wildest adventure you’ve done abroad?",
        "Have you ever slept somewhere unusual like a treehouse or cave?",
        "What’s the longest road trip you’ve ever been on?",
        "Have you ever gotten lost in a city and discovered something amazing?",
        "What’s the most breathtaking view you’ve ever seen?",
        "Have you ever taken a trip on a whim with no plans?",
        "What’s your favorite travel memory with family?",
        "Have you ever been scared during an adventure activity?",
        "What’s the most beautiful beach you’ve visited?",
        "Have you ever traveled somewhere just to try the local drinks or desserts?",
        "What’s the most fun adventure you’ve had in nature?"
    )

    val Weird = listOf(
        "What is the weirdest food you’ve ever tasted?",
        "Have you ever worn mismatched shoes in public by accident?",
        "What is the strangest dream you’ve ever had?",
        "Have you ever talked to yourself out loud in public?",
        "What is the most bizarre thing you’ve ever done on a dare?",
        "Have you ever eaten something just to impress someone?",
        "What is the funniest rumor you’ve heard about yourself?",
        "Have you ever pretended to know someone when you didn’t?",
        "What is the oddest thing you’ve ever collected?",
        "Have you ever had a conversation with an inanimate object?",
        "What is the most ridiculous outfit you’ve worn?",
        "Have you ever tried to invent something strange?",
        "What is the weirdest nickname someone has given you?",
        "Have you ever mistaken a stranger for someone you knew?",
        "What is the strangest thing you’ve ever smelled?",
        "Have you ever danced alone like nobody was watching — and someone was?",
        "What is the oddest thing in your room right now?",
        "Have you ever had an imaginary friend?",
        "What is the weirdest text you’ve ever sent by mistake?",
        "Have you ever eaten something off the floor because it looked clean?",
        "What is the silliest superstition you secretly believe?",
        "Have you ever tried to speak to animals?",
        "What is the weirdest way you’ve injured yourself?",
        "Have you ever worn pajamas all day without realizing it?",
        "What is the strangest thing you’ve ever bought online?",
        "Have you ever laughed so hard you cried in a strange place?",
        "What is the weirdest thing you’ve done when home alone?",
        "Have you ever eaten a bizarre food combination on purpose?",
        "What is the funniest face you can make?",
        "Have you ever worn something backwards by accident?",
        "What is the most awkward thing you’ve said to a stranger?",
        "Have you ever started laughing at the wrong moment?",
        "What is the strangest noise you can make?",
        "Have you ever given something an odd name just for fun?",
        "What is the weirdest outfit you secretly love?",
        "Have you ever talked to your pet like it understood you?",
        "What is the most random object in your bag or pocket?",
        "Have you ever made up a story about yourself to see if people believed it?",
        "What is the strangest compliment you’ve ever received?",
        "Have you ever hidden a snack so no one would eat it?",
        "What is the oddest thing you’ve ever done while half asleep?",
        "Have you ever named a household object?",
        "What is the weirdest photo on your phone?",
        "Have you ever invented a secret handshake with yourself?",
        "What is the strangest thing you’ve ever Googled?",
        "Have you ever tried to see how many grapes you can fit in your mouth?",
        "What is the silliest thing you believed as a kid?",
        "Have you ever sung in the shower at the top of your lungs?",
        "What is the weirdest flavor of ice cream you’ve tried?",
        "Have you ever pretended to be someone else on the phone?",
        "What is the strangest thing you’ve done for a joke?",
        "Have you ever walked into a glass door or wall?",
        "What is the weirdest superstition you’ve heard?",
        "Have you ever made up your own language?",
        "What is the oddest thing you’ve ever written in a notebook?",
        "Have you ever had a funny misunderstanding in public?",
        "What is the strangest excuse you’ve used to get out of something?",
        "Have you ever tried to talk in a fake accent for a whole day?",
        "What is the weirdest thing you’ve ever smelled on purpose?",
        "Have you ever put on clothes inside out and not noticed?",
        "What is the oddest thing you’ve done just to make someone laugh?",
        "Have you ever acted like a spy in public?",
        "What is the weirdest place you’ve fallen asleep?",
        "Have you ever mimicked a celebrity in front of people?",
        "What is the silliest voice you can do?",
        "Have you ever taken a silly selfie in public?",
        "What is the strangest thing you’ve ever whispered to someone?",
        "Have you ever created a silly nickname for yourself?",
        "What is the weirdest thing you’ve done in an elevator?",
        "Have you ever tried to make an animal sound in public?",
        "What is the oddest way you’ve greeted someone?",
        "Have you ever walked around with something on your face and didn’t know?",
        "What is the weirdest excuse you’ve given for being late?",
        "Have you ever invented a dance move nobody else understands?",
        "What is the strangest thing you’ve ever done while bored?",
        "Have you ever put something unusual on pizza?",
        "What is the weirdest prank you’ve ever pulled?",
        "Have you ever worn sunglasses indoors just because?",
        "What is the oddest thing you’ve seen someone do in public?",
        "Have you ever made silly noises while waiting in line?",
        "What is the weirdest place you’ve brushed your teeth?",
        "Have you ever laughed at something you shouldn’t have?",
        "What is the strangest way you’ve answered the phone?",
        "Have you ever given yourself a secret superhero name?",
        "What is the weirdest object you’ve used as a hat?",
        "Have you ever made a funny face at a camera on purpose?",
        "What is the oddest sound you’ve heard someone make?",
        "Have you ever mistaken a mannequin for a real person?",
        "What is the weirdest thing you’ve worn to bed?",
        "Have you ever tried to balance something strange on your head?",
        "What is the strangest thing you’ve eaten at midnight?",
        "Have you ever had an unusual habit you tried to hide?",
        "What is the silliest competition you’ve created?",
        "Have you ever taken a funny photo with a statue?",
        "What is the oddest place you’ve hidden something?",
        "Have you ever made up a weird story about your life?",
        "What is the weirdest thing you’ve done just because you were curious?",
        "Have you ever had a funny accident with food?",
        "What is the strangest thing you’ve seen someone carry on the street?",
        "Have you ever worn something silly just for fun?",
        "What is the weirdest pet name you’ve heard?",
        "Have you ever pretended to be invisible?",
        "What is the oddest thing you’ve done in front of a mirror?",
        "Have you ever invented a strange game?",
        "What is the silliest bet you’ve made?",
        "Have you ever done a weird impression of a teacher or boss?",
        "What is the strangest way you’ve celebrated something?",
        "Have you ever written a strange note to yourself?",
        "What is the oddest thing you’ve done on video call?",
        "Have you ever practiced a strange talent in secret?",
        "What is the weirdest thing you’ve said in your sleep?",
        "Have you ever made up a weird rule that only you follow?",
        "What is the strangest thing you’ve ever worn for fun?",
        "Have you ever sung a song using only silly sounds?",
        "What is the oddest smell you’ve liked?",
        "Have you ever told a bizarre joke that nobody understood?"

    )

    val Funny = listOf(
        "What's the silliest thing you've done in public?",
        "Have you ever worn clothes inside out all day without noticing?",
        "What's the funniest thing you've said by accident?",
        "Have you ever laughed at the wrong time?",
        "What's the weirdest sound you can make?",
        "Have you ever balanced something on your head for fun?",
        "What's the silliest face you can make?",
        "Have you ever made up a funny dance move?",
        "What's the most ridiculous outfit you've worn on purpose?",
        "Have you ever sung a silly song in front of people?",
        "What's the funniest prank you've pulled?",
        "Have you ever eaten food in a weird way just for laughs?",
        "What's the silliest nickname you've had?",
        "Have you ever made a funny voice on the phone?",
        "What's the funniest autocorrect mistake you've sent?",
        "Have you ever pretended to be a movie character?",
        "What's the goofiest selfie you've taken?",
        "Have you ever worn a silly hat in public?",
        "What's the most ridiculous excuse you've given for being late?",
        "Have you ever told a joke nobody got?",
        "What's the funniest misunderstanding you've been part of?",
        "Have you ever played a harmless prank on a friend?",
        "What's the silliest rumor you've started or heard?",
        "Have you ever made someone laugh by accident?",
        "What's the most random thing you've shouted in excitement?",
        "Have you ever giggled at a serious moment?",
        "What's the funniest costume you've worn?",
        "Have you ever had to leave a room because you couldn't stop laughing?",
        "What's the goofiest picture on your phone?",
        "Have you ever made a silly bet with someone?",
        "What's the most ridiculous dare you've done?",
        "Have you ever spoken in a fake accent just for fun?",
        "What's the funniest dance you've done or seen?",
        "Have you ever played air guitar in public?",
        "What's the silliest face you've made in a photo?",
        "Have you ever made up a nonsense word?",
        "What's the funniest thing you've done on a video call?",
        "Have you ever tried to sing with a mouth full of food?",
        "What's the most absurd outfit combination you've worn?",
        "Have you ever pretended to be a famous singer in front of a mirror?",
        "What's the silliest thing you've said half asleep?",
        "Have you ever made someone laugh until they cried?",
        "What's the most ridiculous thing you've done for attention?",
        "Have you ever invented a silly handshake?",
        "What's the funniest text you've sent by mistake?",
        "Have you ever had an awkward laugh attack?",
        "What's the silliest photo pose you've done?",
        "Have you ever tried copying a cartoon voice?",
        "What's the funniest thing you've done at a party?",
        "Have you ever worn mismatched socks on purpose?",
        "What's the goofiest nickname you've given someone?",
        "Have you ever done an over-the-top celebration dance?",
        "What's the most random thing you've Googled for fun?",
        "Have you ever played an imaginary instrument in public?",
        "What's the funniest message you've written on a note?",
        "Have you ever made a silly face in a serious picture?",
        "What's the most ridiculous food combo you've tried?",
        "Have you ever laughed so hard you couldn't breathe?",
        "What's the funniest thing that happened in class or a meeting?",
        "Have you ever imitated a teacher or boss for laughs?",
        "What's the silliest voice you've used on purpose?",
        "Have you ever made up a funny song on the spot?",
        "What's the funniest mistake you've made while texting?",
        "Have you ever turned a boring chore into a silly game?",
        "What's the most absurd place you've danced?",
        "Have you ever laughed at your own joke?",
        "What's the weirdest noise you've made just to be funny?",
        "Have you ever done a silly walk to make someone laugh?",
        "What's the funniest thing you've drawn or doodled?",
        "Have you ever worn something outrageous for a laugh?",
        "What's the goofiest face you've made in a mirror?",
        "Have you ever turned a conversation into a comedy routine?",
        "What's the funniest thing you've overheard?",
        "Have you ever had a laughing fit you couldn't stop?",
        "What's the most random thing you've shouted in a crowd?",
        "Have you ever done a fake magic trick for fun?",
        "What's the funniest snap or story you've posted?",
        "Have you ever acted out a movie scene with friends?",
        "What's the goofiest TikTok or reel you've tried?",
        "Have you ever made up a silly holiday?",
        "What's the funniest way you've answered a question?",
        "Have you ever done a crazy victory dance?",
        "What's the most ridiculous thing you've worn on your head?",
        "Have you ever made funny faces at a baby or pet?",
        "What's the silliest thing you've done while bored?",
        "Have you ever shared a ridiculous secret just for laughs?",
        "What's the funniest picture you've photobombed?",
        "Have you ever tried to keep a straight face and failed?",
        "What's the most absurd voice impression you've done?",
        "Have you ever laughed at something you didn't understand?",
        "What's the silliest award you could give yourself?",
        "Have you ever invented a nonsense rule in a game?",
        "What's the funniest video you've made?",
        "Have you ever turned an argument into a joke?",
        "What's the most outrageous snack you've made?",
        "Have you ever laughed at an inappropriate time?",
        "What's the funniest misheard lyric you've sung?",
        "Have you ever done a silly pose for a group photo?",
        "What's the strangest way you've made someone laugh?",
        "Have you ever made up a ridiculous rumor about yourself?",
        "What's the funniest typo you've sent to a teacher or boss?",
        "Have you ever worn something backwards on purpose?",
        "What's the most random thing you've said during a dare?",
        "Have you ever created a silly voice for your pet?",
        "What's the funniest sound effect you've made?",
        "Have you ever practiced a comedy routine in secret?",
        "What's the most absurd challenge you've accepted?",
        "Have you ever tried to speak only in rhymes?",
        "What's the goofiest compliment you've given someone?",
        "Have you ever laughed so hard you fell over?",
        "What's the funniest thing you've caught on camera?",
        "Have you ever done a silly imitation of a celebrity?",
        "What's the most ridiculous thing you've written in a notebook?",
        "Have you ever made a funny face at a stranger?",
        "What's the silliest question you've asked in class or at work?",
        "Have you ever started laughing during a serious talk?",
        "What's the funniest pet trick you've seen?",
        "Have you ever made someone laugh just with a look?",
        "What's the weirdest laugh you've ever done?"

    )

    val Dreams = listOf(
            "What's your biggest dream in life?",
            "If you could have any job, what would it be?",
            "Have you ever given up on a goal? Why?",
            "What's something you've always wanted to learn?",
            "Where do you see yourself in 5 years?",
            "What motivates you the most?",
            "Have you ever done something you thought was impossible?",
            "If money wasn't a problem, what would you do every day?",
            "What's one skill you wish you could master instantly?",
            "Has anyone inspired you to follow a dream?",
            "What's a dream you're currently working on?",
            "If you could live anywhere, where would it be?",
            "What's the most important goal you want to reach this year?",
            "Have you ever taken a big risk for a dream?",
            "What's a childhood ambition you still remember?",
            "What's a dream that both excites and scares you?",
            "If you could start a business, what would it be?",
            "Have you ever made a plan that didn't work out?",
            "What inspires you when you feel stuck?",
            "If you could have one superpower to reach your goals, what would it be?",
            "What's a dream you're too scared to share?",
            "Have you ever surprised yourself by achieving something?",
            "What's the best compliment you've received about your talents?",
            "If you could switch careers without worry, what would you do?",
            "What's a small goal you're proud of completing recently?",
            "Have you ever helped someone else reach their dream?",
            "What dream would you follow if you knew you couldn't fail?",
            "Who has a life path you admire?",
            "What's a passion you've never told anyone about?",
            "Have you ever changed your mind about your goals?",
            "What's a personal project you've always wanted to start?",
            "If you could learn any language or skill instantly, what would it be?",
            "What keeps you going when things get tough?",
            "What's one goal that makes you feel truly alive?",
            "Have you ever tried something that seemed impossible?",
            "If you could achieve one big thing this year, what would it be?",
            "Who encourages your ambitions the most?",
            "What's a dream that still excites you when you think about it?",
            "Have you ever worked hard for something and felt it was worth it?",
            "What's a life goal you've had since childhood?",
            "If you could make one wish come true, what would it be?",
            "Have you ever made a plan that completely changed your life?",
            "What's a dream that pushes you out of your comfort zone?",
            "What would you do if you knew you couldn't fail?",
            "Have you ever helped someone achieve a dream?",
            "What's your proudest accomplishment so far?",
            "If you could inspire someone, what dream would you encourage them to follow?",
            "What's one goal you hope to achieve in the next 10 years?",
            "Have you ever felt like giving up on a big goal?",
            "If you could redo one choice to follow a dream, what would it be?",
            "What's the one thing that drives you every day?",
            "What did you want to be when you were little and why did that change?",
            "What's a secret dream you're working on?",
            "If money wasn't an issue, what would you do with your life?",
            "What's a dream you gave up on but still think about?",
            "Where do you see yourself in 10 years?",
            "What's a goal you're afraid to tell people about?",
            "What's a skill you wish you had to help your dreams?",
            "Who inspires you most to go after what you want?",
            "What's the biggest risk you've taken for a dream?",
            "What's one thing you'd do if you knew you couldn't fail?",
            "What does your perfect life look like?",
            "What's a dream unrelated to work that you have?",
            "What's one step you can take this month toward a big goal?",
            "What's a childhood dream you still want?",
            "What's stopping you from going after what you really want?",
            "If you could start any business, what would it be?",
            "What's a place you dream of living one day?",
            "What's a goal you reached that meant the most to you?",
            "What's something you want to learn or master?",
            "What would you do if you had one extra hour each day?",
            "What's a surprising dream you have?",
            "What's one thing you want to be remembered for?",
            "If you could change one thing about your life path, what would it be?",
            "What's a small dream that would make you really happy?",
            "What's a goal you're glad you didn't achieve?",
            "What does success mean to you?",
            "What's one adventure you still want to have?",
            "What's a dream too big to say out loud?",
            "What's one thing you want to accomplish before a milestone age?",
            "If you could tell your younger self one thing about dreams, what would it be?"

    )
    val Random = listOf("What is your biggest dream in life?",
        "What is a relationship deal-breaker for you?",
        "What is the most embarrassing thing you’ve ever done in public?",
        "Who is your closest friend and why?",
        "Have you ever had a secret crush on a friend?",
        "What’s the sweetest thing someone has done for you in a relationship?",
        "What is the most romantic gesture you’ve ever planned?",
        "What is your opinion on friends with benefits?",
        "What is the boldest thing you’ve done to impress a crush?",
        "What’s the funniest thing you’ve done to get someone’s attention?",
        "What is one thing you look for in a best friend?",
        "What’s the nicest surprise a partner has given you?",
        "What’s the strangest food you’ve ever tried on a date?",
        "What’s your favorite memory with friends?",
        "What is a secret ambition you’ve never shared?",
        "What’s the funniest thing that’s happened to you at work or school?",
        "What’s your favorite way to spend a weekend with friends?",
        "What’s the most daring thing you’ve ever done for someone you like?",
        "What’s a compliment from a crush you’ll never forget?",
        "What’s your favorite travel destination so far?",
        "What’s a weird tradition you share with a friend?",
        "What is the most romantic trip you’ve taken or want to take?",
        "What’s the wildest party you’ve attended with friends?",
        "What’s a silly nickname you’ve given a crush or partner?",
        "What’s the funniest inside joke you have with someone?",
        "What is your opinion on flirting while in a relationship?",
        "What is your favorite memory from childhood with friends?",
        "What’s the boldest text you’ve sent someone you like?",
        "What’s the craziest dare you’ve accepted with friends?",
        "What’s your favorite type of date night?",
        "What is a spicy question you’ve always wanted to ask a partner?",
        "What’s a quality you value most in friendships?",
        "What is your opinion on casual dating apps?",
        "What’s the weirdest coincidence with someone you like?",
        "What’s the most thoughtful gift you’ve given a friend?",
        "What’s the most exciting thing you’ve done as a couple?",
        "What’s one thing you wish you could tell your crush?",
        "What’s the best advice a friend has given you?",
        "What’s a romantic movie scene you wish could happen to you?",
        "What’s the funniest photo on your phone with friends?",
        "What’s a boundary that’s important in close friendships?",
        "What’s your favorite couple activity?",
        "What is one question you’ve always wanted to ask a crush?",
        "What’s an 18+ movie or show you secretly enjoy?",
        "What’s the most fun you’ve had with friends recently?",
        "What’s the boldest thing you’d try with a partner if they agreed?",
        "What’s a memory with friends that makes you laugh every time?",
        "What’s the weirdest thing a crush has said to you?",
        "What’s the cutest text you’ve received?",
        "What is your opinion on kissing games at parties?",
        "What’s the best compliment you’ve given a friend?",
        "What is your favorite thing about being in love?",
        "What’s one silly argument you’ve had with a friend?",
        "What’s the longest friendship you’ve had?",
        "What’s something you find attractive in someone (non-physical)?",
        "What’s the funniest misunderstanding with a crush?",
        "What’s the most meaningful thing you’ve done for a friend?",
        "What’s a romantic song that reminds you of someone?",
        "What’s an adventurous date you’d love to try?",
        "What’s one way you cheer up friends when they’re sad?",
        "What’s the most awkward thing you’ve said to someone you liked?",
        "What’s a habit you adore in a partner?",
        "What’s the most heartwarming message from a friend?",
        "What is your opinion on trying new things with a partner?",
        "What’s your favorite silly activity with friends?",
        "What’s a secret about love you’ve never told anyone?",
        "What’s a joke only you and a friend understand?",
        "What’s the most memorable first date you’ve had?",
        "What’s a quality you love about your crush?",
        "What is your opinion on keeping secrets in dating?",
        "What’s your go-to fun plan with friends?",
        "What’s the silliest reason you’ve blushed?",
        "What’s a romantic spot you’d like to visit?",
        "What’s something you admire about your best friend?",
        "What’s an 18+ topic you’re curious to discuss with someone?",
        "What’s the funniest dare you’ve done in front of friends?",
        "What’s the most playful thing a partner has done for you?",
        "What’s a silly question you’d ask a crush to make them laugh?",
        "What’s the boldest compliment you’ve given someone?",
        "What’s your favorite thing about late-night talks with friends?",
        "What’s an exciting adventure you’d share with someone you love?",
        "What’s a moment with a crush you’ll always remember?",
        "What’s a romantic text you wish someone would send you?",
        "What’s your opinion on being friends with an ex?",
        "What’s the most supportive thing a friend has done for you?",
        "What’s a memory that made you fall for someone?",
        "What’s a fun challenge you’d do with a partner?",
        "What’s your favorite silly memory with a friend?",
        "What’s an 18+ opinion you think couples should discuss?",
        "What’s the cutest nickname you’ve been given?",
        "What’s the funniest story your friends know about you?",
        "What’s the sweetest way someone’s confessed feelings to you?",
        "What’s a personal boundary you value in friendships?",
        "What’s a flirty compliment you’d give a crush?",
        "What’s the most unforgettable adventure with friends?",
        "What’s your favorite thing about double dates?",
        "What’s the boldest truth you’ve shared with a partner?",
        "What’s one way you show appreciation to friends?",
        "What’s the funniest dance moment at a party?",
        "What’s an experience you’d love to share with someone special?",
        "What’s a daring thing you’ve done just for fun with friends?",
        "What’s the cutest thing you’ve done for someone you like?",
        "What’s your opinion on romantic surprises?",
        "What’s a hobby you’d love to try with a friend?",
        "What’s an 18+ conversation you think builds trust in couples?",
        "What’s the most fun you’ve had flirting?",
        "What’s the funniest pet story with friends?",
        "What’s a random kind act you’ve done for someone?",
        "What’s the most supportive text from a friend?",
        "What’s the most thoughtful date you’ve been on?",
        "What’s a funny thing you’ve done to avoid an awkward moment?",
        "What’s your favorite cozy activity with friends?",
        "What’s the most meaningful compliment from a crush?",
        "What’s an adventurous thing you’d do if you weren’t scared?",
        "What’s a gift you’d love to get from a partner?",
        "What’s the funniest thing your friend group has done together?",
        "What’s a romantic goal you’d love to achieve?",
        "What’s a moment when you felt closest to friends?",
        "What’s an 18+ experience you’d only try with full trust?",
        "What’s the most hilarious face-off with a friend?",
        "What’s your favorite sweet gesture in a relationship?",
        "What’s a wild bucket-list item you’d do with friends?",
        "What’s the funniest pickup line you’ve heard?",
        "What’s the most heartwarming friendship story you know?",
        "What’s a silly secret handshake you’ve made?",
        "What’s one rule you and your friends never break?",
        "What’s an affectionate habit you enjoy in couples?",
        "What’s the funniest reaction a crush has had to your text?",
        "What’s a moment when you felt truly loved by someone?",
        "What’s a funny code word you use with friends?",
        "What’s an opinion you have about romantic gestures?",
        "What’s the cutest friendship tradition you have?",
        "What’s the boldest adventure you’d take with a crush?",
        "What’s a meaningful way you’ve supported someone?",
        "What’s an 18+ boundary you think is important?",
        "What’s a flirty joke you’d use on someone you like?",
        "What’s a romantic idea you’ve secretly imagined?",
        "What’s one reason you’re grateful for your friends?",
        "What’s a lighthearted secret you’ve shared with a crush?",
        "What’s a fun thing couples should try together?",
        "What’s your favorite memory of laughing with friends?",
        "What’s a bold question you’d ask on a date?",
        "What’s a caring gesture that’s stayed with you?",
        "What’s the cutest random act you’ve seen between friends?",
        "What’s your opinion on honest talks in relationships?",
        "What’s the silliest compliment you’ve received from friends?",
        "What’s an 18+ topic you think people should talk about openly?",
        "What’s the sweetest way to say ‘I care’?",
        "What’s the funniest dare story among your friends?",
        "What’s one thing that makes you feel valued in love?",
        "What’s the most unique party moment with friends?",
        "What’s a playful moment with someone you liked?",
        "What’s a goal you’d love to achieve with a partner?",
        "What’s the funniest misunderstanding in a group chat?",
        "What’s the best thing about long-term friendships?",
        "What’s an affectionate message you’d love to send?",
        "What’s the most wholesome compliment you’ve gotten from a crush?",
        "What’s a daring date idea you’d plan?",
        "What’s the most random funny memory with friends?",
        "What’s your opinion on sharing feelings early in dating?",
        "What’s the sweetest word you’ve been called?",
        "What’s one thing you’d plan for your best friend’s birthday?",
        "What’s the funniest competition you’ve had with friends?",
        "What’s an 18+ tip you’d give about healthy boundaries?",
        "What’s the best romantic advice you’ve received?",
        "What’s a secret wish you’ve made for someone close?",
        "What’s the funniest reaction from friends to your news?",
        "What’s a heartfelt message you’ve sent to a crush?",
        "What’s the coolest activity you’ve tried with a partner?",
        "What’s a silly thing friends dared you to do?",
        "What’s one way you celebrate friends’ successes?",
        "What’s the most surprising thing a crush has done for you?",
        "What’s a romantic playlist you’d make for someone?",
        "What’s the funniest video you’ve shared in a group?",
        "What’s one reason you value friendship so much?",
        "What’s an 18+ truth about relationships people should respect?",
        "What’s the funniest excuse you’ve used to text someone you like?",
        "What’s a random gesture that made you smile?",
        "What’s the cutest adventure you’ve had with someone special?",
        "What’s the best thing about laughing with friends late at night?",
        "What’s an affectionate way you’ve comforted someone?",
        "What’s the funniest compliment you’ve given friends?",
        "What’s a fun memory you’d love to repeat with a partner?",
        "What’s a bold way you’ve confessed feelings?",
        "What’s a silly dance moment shared with friends?",
        "What’s the most charming thing a crush has done?",
        "What’s a small thing friends do that means a lot?",
        "What’s a romantic boundary you think couples should discuss?",
        "What’s the funniest way you’ve surprised someone you like?",
        "What’s the best bonding activity with friends?",
        "What’s a fun challenge for couples you’d suggest?",
        "What’s the most unexpected kindness from a crush?",
        "What’s a friendly tradition you want to keep forever?",
        "What’s an 18+ conversation that helped you understand someone better?",
        "What’s a meaningful compliment you’ve given to someone special?",
        "What’s the funniest group photo moment you remember?",
        "What’s a cute routine you and your partner share?",
        "What’s the boldest romantic message you’ve sent?",
        "What’s a quirky activity friends and couples can both enjoy?",
        "What’s your opinion on experimenting with partners?",
        "What’s a flirty text you’ve always wanted to receive?",
        "What’s a secret about attraction you’d only tell close friends?",
        "What’s a boundary you think is important in adult friendships?",
        "What’s a sweet thing someone has whispered to you?",
        "What’s a funny story about your first crush?",
        "What’s the boldest romantic plan you’ve imagined?",
        "What’s a supportive message you’ve sent after a breakup?",
        "What’s the cutest message chain you’ve had with a partner?",
        "What’s an 18+ opinion on keeping intimacy private?",
        "What’s the most fun double-date game you’ve played?",
        "What’s an adventure you’d plan with your partner for a weekend?",
        "What’s the most unexpected compliment you’ve ever received?",
        "What’s a romantic idea you’d love someone to try on you?",
        "What’s the funniest way you’ve shown someone you cared?",
        "What’s a playful boundary you’d set with friends?",
        "What’s a late-night talk you’ll never forget?",
        "What’s your opinion on romantic surprises vs planned gestures?",
        "What’s a flirty emoji you secretly love to use?",
        "What’s a thoughtful way to celebrate a friend’s success?",
        "What’s the sweetest way a crush has supported you?",
        "What’s a fun bucket list activity for couples or friends?",
        "What’s an affectionate memory that still makes you smile?",
        "What’s your opinion on loyalty in close friendships?",
        "What’s an 18+ opinion about open discussions with partners?",
        "What’s the most creative date idea you’ve had?",
        "What’s a funny group photo idea you’d try?",
        "What’s one thing you admire about couples you know?",
        "What’s the cutest way you’ve helped a shy friend?",
        "What’s a daring thing you’ve done to impress someone?",
        "What’s a sweet morning text you’d like to get?",
        "What’s your opinion on mixing friendship and romance?",
        "What’s a silly but meaningful inside joke with someone?",
        "What’s the most playful compliment you’ve given?",
        "What’s an affectionate surprise you’ve prepared for someone?",
        "What’s the funniest time a crush has made you laugh?",
        "What’s a supportive way you’ve helped friends through love issues?"
    )
    val truthMap: Map<String, List<String>> = mapOf(
        "Deep" to Deep,
        "Embarrassing" to Embarrassing,
        "Favorites" to Favorites,
        "Friendship" to Friendship,
        "NeverHaveIEver" to NeverHaveIEver,
        "Secrets" to Secrets,
        "Romantic" to Romantic,
        "Spicy" to Spicy,
        "Travel" to Travel,
        "Weird" to Weird,
        "Funny" to Funny,
        "Dreams" to Dreams,
        "Random" to Random
    )

    fun getTruth(dare: String): List<String>? = truthMap[dare]
}